<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>10 Análisis de Datos Cualitativos. | R-Stars: La Guía</title>
<meta name="author" content="Miguel-Ángel Tarancón">
<meta name="description" content="10.1 Introducción. En numerosas ocasiones la información con que el analista debe enfrentarse es de naturaleza cualitativa, esto es, la información se recoge en características no numéricas o...">
<meta name="generator" content="bookdown 0.44 with bs4_book()">
<meta property="og:title" content="10 Análisis de Datos Cualitativos. | R-Stars: La Guía">
<meta property="og:type" content="book">
<meta property="og:url" content="https://teckel71.github.io/RStars-book/análisis-de-datos-cualitativos..html">
<meta property="og:image" content="https://teckel71.github.io/RStars-book/figuras/Portada_v3-2.jpg">
<meta property="og:description" content="10.1 Introducción. En numerosas ocasiones la información con que el analista debe enfrentarse es de naturaleza cualitativa, esto es, la información se recoge en características no numéricas o...">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="10 Análisis de Datos Cualitativos. | R-Stars: La Guía">
<meta name="twitter:description" content="10.1 Introducción. En numerosas ocasiones la información con que el analista debe enfrentarse es de naturaleza cualitativa, esto es, la información se recoge en características no numéricas o...">
<meta name="twitter:image" content="https://teckel71.github.io/RStars-book/figuras/Portada_v3-2.jpg">
<!-- JS --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script><script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script><script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet">
<script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script><link href="libs/Inter-0.4.10/font.css" rel="stylesheet">
<link href="libs/JetBrains_Mono-0.4.10/font.css" rel="stylesheet">
<link href="libs/Inter_Tight-0.4.10/font.css" rel="stylesheet">
<script src="libs/bs3compat-0.9.0/transition.js"></script><script src="libs/bs3compat-0.9.0/tabs.js"></script><script src="libs/bs3compat-0.9.0/bs3compat.js"></script><link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet">
<script src="libs/bs4_book-1.0.0/bs4_book.js"></script><script src="libs/kePrint-0.0.1/kePrint.js"></script><link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet">
<script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script><!-- CSS --><style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
<style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
          margin-bottom: 0em;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
<link rel="stylesheet" href="assets/styles.css">
</head>
<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book"><a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="">R-Stars: La Guía</a>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
</form>

      <nav aria-label="Table of contents"><h2>Table of contents</h2>
        <ul class="book-toc list-unstyled">
<li><a class="" href="index.html"></a></li>
<li><a class="" href="prefacio.html">Prefacio</a></li>
<li><a class="" href="introducci%C3%B3n..html"><span class="header-section-number">1</span> Introducción.</a></li>
<li><a class="" href="almacenando-y-manipulando-datos..html"><span class="header-section-number">2</span> Almacenando y manipulando datos.</a></li>
<li><a class="" href="gr%C3%A1ficos..html"><span class="header-section-number">3</span> Gráficos.</a></li>
<li><a class="" href="estad%C3%ADstica-descriptiva..html"><span class="header-section-number">4</span> Estadística descriptiva.</a></li>
<li><a class="" href="an%C3%A1lisis-previo-de-datos..html"><span class="header-section-number">5</span> Análisis previo de datos.</a></li>
<li><a class="" href="componentes-principales..html"><span class="header-section-number">6</span> Componentes principales.</a></li>
<li><a class="" href="an%C3%A1lisis-cl%C3%BAster..html"><span class="header-section-number">7</span> Análisis Clúster.</a></li>
<li><a class="" href="an%C3%A1lisis-de-la-varianza..html"><span class="header-section-number">8</span> Análisis de la varianza.</a></li>
<li><a class="" href="an%C3%A1lisis-de-regresi%C3%B3n-lineal-m%C3%BAltiple..html"><span class="header-section-number">9</span> Análisis de Regresión Lineal Múltiple.</a></li>
<li><a class="active" href="an%C3%A1lisis-de-datos-cualitativos..html"><span class="header-section-number">10</span> Análisis de Datos Cualitativos.</a></li>
<li><a class="" href="bibliograf%C3%ADa.html">Bibliografía</a></li>
</ul>

        <div class="book-extra">
          
        </div>
      </nav>
</div>
  </header><main class="col-sm-12 col-md-9 col-lg-7" id="content"><div id="análisis-de-datos-cualitativos." class="section level1" number="10">
<h1>
<span class="header-section-number">10</span> Análisis de Datos Cualitativos.<a class="anchor" aria-label="anchor" href="#an%C3%A1lisis-de-datos-cualitativos."><i class="fas fa-link"></i></a>
</h1>
<div id="introducción.-6" class="section level2" number="10.1">
<h2>
<span class="header-section-number">10.1</span> Introducción.<a class="anchor" aria-label="anchor" href="#introducci%C3%B3n.-6"><i class="fas fa-link"></i></a>
</h2>
<p>En numerosas ocasiones la información con que el analista debe enfrentarse es de naturaleza <strong>cualitativa</strong>, esto es, la información se recoge en características no numéricas o <strong>atributos</strong> (o factores o variables categóricas o cualitativas). Cuando ocurre esto, es necesario recurrir a técnicas de explotación específicas para este tipo de datos. Así, en este capítulo vamos a explorar algunos métodos para extraer información útil cuando los datos de <strong>los que disponemos son categóricos.</strong></p>
<p>En estos casos, la información suele sintetizarse y presentarse mediante las denominadas “<strong>tablas de contingencia</strong>”. En este tipo de tablas, se muestran las frecuencias conjuntas, es decir, el número de casos que comparten los distintos niveles o categorías de los diferentes factores.</p>
<p>Cuando se trabaja con varios factores o atributos, representados en su correspondiente tabla de contingencia, uno de los análisis más interesantes es determinar si existe <strong>asociación</strong> entre los factores o atributos. Esto es, si se aprecia algún tipo de relación estadística entre estas variables categóricas o cualitativas, en el sentido de si se puede afirmar que el hecho de que los casos de la muestra tomen ciertos niveles o categorías en unos factores, hace que estos mismos casos tiendan a tomar ciertos niveles o categorías de otro u otros factores.</p>
</div>
<div id="tablas-de-contingencia-y-asociación-entre-dos-atributos-o-factores." class="section level2" number="10.2">
<h2>
<span class="header-section-number">10.2</span> Tablas de contingencia, y asociación entre dos atributos o factores.<a class="anchor" aria-label="anchor" href="#tablas-de-contingencia-y-asociaci%C3%B3n-entre-dos-atributos-o-factores."><i class="fas fa-link"></i></a>
</h2>
<p>Comenzaremos con el caso más sencillo, en el que los casos de nuestra muestra se distribuyen entre las categorías o niveles de dos atributos o factores. En este caso, la tabla de contingencia que presente los datos de esta situación será una simple tabla de doble entrada. En las filas de la tabla se dispondrán las categorías de uno de los factores, y en las columnas de la tabla se situarán las categorías del otro factor.</p>
<p>Para ilustrar el tratamiento de una tabla de contingencia bidimensional, vamos a trabajar con los datos correspondientes a 51 empresas de generación eléctrica presentes en el archivo de Microsoft® Excel® “<a href="https://docs.google.com/spreadsheets/d/1N5QIRKbm6OKAOaN8DB2YFDptpZ_0pbPc/edit?usp=sharing&amp;ouid=115375878280465826079&amp;rtpof=true&amp;sd=true">eolica_contingencia.xlsx</a>”. Este archivo cuenta con 3 hojas, los datos en cuestión se encuentran en la que tiene por nombre “Datos”.</p>
<p>Dentro de “Datos”, existen dos variables categóricas, atributos o factores: la variable DIMENSION, que tiene, a su vez, tres categorías dependiendo del número de empresas que integradas en la matriz de la empresa en cuestión (“GRANDE”, “MEDIA” o “REDUCIDA”); y la variable VALORACION, que cuenta con tres categorías dependiendo de la opnión de un panel de expertos en cuanto a la situación económica de la empresa (“OPTIMA”, “NORMAL”, “PESIMA”). Nuestra intención es analizar si existe <strong>evidencia sobre asociación</strong> entre las dos variables categóricas, en el sentido de que los casos tienden a concentrarse con cierta facilidad en ciertas combinaciones de categorías de uno y otro factor, y/o a no posicionarse en otras combinaciones; o si por el contrario no se puede afirmar que exista asociación de este tipo.</p>
<p>El código de R que iremos aplicando se encuentra en el <em>script</em> “<a href="https://drive.google.com/file/d/1u8gJa3jQH2cwuQ8KsISQ9esHKrFAO_au/view?usp=sharing">correspondencias_eolica.R</a>”. Trabajaremos en un proyecto específico de RStudio, si así lo valoramos como conveniente (en este ejemplo, el proyecto “correspondencias”).</p>
<p>Al abrir el <em>script</em> en el editor de RStudio, lo primero que veremos será la instrucción para limpiar la memoria de objetos. Tras ello, se procede a la importación de los datos del fichero de <em>Excel</em>. Tras importar las variables, se procede a ajustar la importación para que la primera columna pase a ser el nombre de los casos (filas) del <em>data frame</em> que recibe y almacena los datos. Este <em>data frame</em> se denomina, por ejmplo, “eolicas”. Con un <code><a href="https://rdrr.io/r/base/summary.html">summary()</a></code> comprobamos que las variables se han importado correctamente:</p>
<div class="sourceCode" id="cb355"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Analisis de correspondencias simple de eolicas</span></span>
<span><span class="co"># Disculpen por la falta de tildes!</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># DATOS</span></span>
<span></span>
<span>  <span class="co"># Importando datos</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://readxl.tidyverse.org">readxl</a></span><span class="op">)</span></span>
<span>    <span class="va">eolicas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_excel</a></span><span class="op">(</span><span class="st">"eolica_contingencia.xlsx"</span>, sheet <span class="op">=</span><span class="st">"Datos"</span><span class="op">)</span></span>
<span>    <span class="va">eolicas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">eolicas</span>, row.names <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span> <span class="op">(</span><span class="va">eolicas</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      MARGEN            SOLVENCIA          COM           
##  Min.   :-1159.297   Min.   :-66.95   Length:51         
##  1st Qu.:    5.677   1st Qu.: 16.32   Class :character  
##  Median :   34.252   Median : 42.98   Mode  :character  
##  Mean   :   47.643   Mean   : 45.76                     
##  3rd Qu.:   53.388   3rd Qu.: 80.31                     
##  Max.   : 1790.123   Max.   :100.00                     
##  NA's   :9                                              
## 
##      FJUR                ING                NCOMP      
##  Length:51          Min.   :2.940e-01   Min.   :    0  
##  Class :character   1st Qu.:9.759e+01   1st Qu.:    1  
##  Mode  :character   Median :1.241e+03   Median :   31  
##                     Mean   :1.071e+04   Mean   : 1655  
##                     3rd Qu.:6.766e+03   3rd Qu.:  170  
##                     Max.   :2.559e+05   Max.   :72434  
##                     NA's   :9                          
## 
##       RES                ACTIVO              FPIOS          
##  Min.   :-3274.323   Min.   :2.990e+00   Min.   : -1919.42  
##  1st Qu.:    0.298   1st Qu.:1.605e+02   1st Qu.:    71.57  
##  Median :   57.760   Median :2.420e+03   Median :   888.78  
##  Mean   : 2203.986   Mean   :6.790e+04   Mean   :  8991.25  
##  3rd Qu.:  622.075   3rd Qu.:1.638e+04   3rd Qu.:  6413.52  
##  Max.   :78290.000   Max.   :2.429e+06   Max.   :148251.00  
##  NA's   :5                                                  
## 
##      RENECO             RENFIN           LIQUIDEZ      
##  Min.   :-103.156   Min.   :-596.79   Min.   :  0.006  
##  1st Qu.:   0.000   1st Qu.:   0.00   1st Qu.:  0.667  
##  Median :   3.165   Median :  12.94   Median :  1.833  
##  Mean   :   6.559   Mean   :  10.94   Mean   : 17.853  
##  3rd Qu.:  13.329   3rd Qu.:  37.99   3rd Qu.:  6.010  
##  Max.   :  95.013   Max.   : 144.04   Max.   :541.752  
##                                       NA's   :2        
## 
##     APALANCA          AUTOFIN        DIMENSION        
##  Min.   :-312.62   Min.   :-0.401   Length:51         
##  1st Qu.:   0.00   1st Qu.: 0.243   Class :character  
##  Median :  18.73   Median : 0.508   Mode  :character  
##  Mean   : 333.41   Mean   : 3.468                     
##  3rd Qu.: 266.68   3rd Qu.: 4.093                     
##  Max.   :6197.54   Max.   :42.156                     
##                    NA's   :20                         
## 
##    AUTOFINA          VALORACION       
##  Length:51          Length:51         
##  Class :character   Class :character  
##  Mode  :character   Mode  :character</code></pre>
<p>A continuación, creamos otro <em>data frame</em>, de nombre, por ejemplo, “originales”, con los dos atributos analizados: el factor DIMENSION y el factor VALORACION. Se comprueba si existen observaciones con <em>missing values</em> y, en tal caso, se eliminan dichas observaciones aplicando el filtro apropiado, a partir de la función <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> del paquete <a href="https://dplyr.tidyverse.org">dplyr</a>:</p>
<div class="sourceCode" id="cb357"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="co"># Seleccionando factores/atributos para el analisis</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span>    <span class="va">originales</span><span class="op">&lt;-</span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">eolicas</span>, <span class="va">DIMENSION</span>, <span class="va">VALORACION</span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span> <span class="op">(</span><span class="va">originales</span><span class="op">)</span></span></code></pre></div>
<pre><code>##   DIMENSION          VALORACION       
##  Length:51          Length:51         
##  Class :character   Class :character  
##  Mode  :character   Mode  :character</code></pre>
<div class="sourceCode" id="cb359"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="co"># Identificando missing values.</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/visdat/">visdat</a></span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://docs.ropensci.org/visdat/reference/vis_miss.html">vis_miss</a></span><span class="op">(</span><span class="va">originales</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-299-1.png" width="672"></div>
<div class="sourceCode" id="cb360"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">originales</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">DIMENSION</span><span class="op">)</span> <span class="op">|</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">VALORACION</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>      <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">DIMENSION</span>, <span class="va">VALORACION</span><span class="op">)</span>  </span></code></pre></div>
<pre><code>## [1] DIMENSION  VALORACION
## &lt;0 rows&gt; (o 0- extensión row.names)</code></pre>
<div class="sourceCode" id="cb362"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">originales</span> <span class="op">&lt;-</span> <span class="va">originales</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>      <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">DIMENSION</span><span class="op">)</span> <span class="op">&amp;</span> <span class="op">!</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">VALORACION</span><span class="op">)</span><span class="op">)</span>  </span></code></pre></div>
<p>En el ejemplo, se comprueba que no existen casos con <em>missing values</em>, por lo que la tabla queda en blanco y no se descarta ninguna observación.</p>
<p>La siguiente etapa es la construcción de la “<strong>tabla de contingencia</strong>”. La función fundamental es <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> que, como sabemos, hace un recuento de los casos (frecuencias) en los que una variable toma un determinado valor (o en los que un atributo adopta una determinada categoría o nivel). Cuando esta función se aplica a más de una variable o atributo, hace un recuento de los casos que adoptan las posibles combinacionesse entre valores/categorías o niveles de las variables o atributos implicados. Cuando se trata de dos atributos, por tanto, <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> construye una tabla de contingencia mediante la formulación de una tabla de doble entrada. En nuestro ejemplo, a la tabla de contingencia la hemos denominado, por ejemplo, “tab.originales”. Luego, la hemos presentado con un formato de tabla elaborado con la función <code><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable()</a></code> del paquete <a href="https://yihui.org/knitr/">knitr</a>, y algunas funciones adicionales del paquete <a href="http://haozhu233.github.io/kableExtra/">kableExtra</a>:</p>
<div class="sourceCode" id="cb363"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># TABLA DE CONTINGENCIA</span></span>
<span></span>
<span>  <span class="va">tab.originales</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">originales</span><span class="op">)</span></span>
<span></span>
<span> <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://yihui.org/knitr/">knitr</a></span><span class="op">)</span></span>
<span> <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span> <span class="va">knitr.table.format</span> <span class="op">=</span> <span class="st">"html"</span></span>
<span></span>
<span> <span class="fu"><a href="https://rdrr.io/r/stats/addmargins.html">addmargins</a></span><span class="op">(</span><span class="va">tab.originales</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>format <span class="op">=</span> <span class="va">knitr.table.format</span>,</span>
<span>        caption<span class="op">=</span><span class="st">"Empresas eólicas"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>full_width <span class="op">=</span> <span class="cn">F</span>,</span>
<span>                bootstrap_options <span class="op">=</span> <span class="st">"striped"</span>, <span class="st">"bordered"</span>, <span class="st">"condensed"</span>,</span>
<span>                position <span class="op">=</span> <span class="st">"center"</span>,</span>
<span>                font_size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/add_header_above.html">add_header_above</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span>DIMENSION <span class="op">=</span> <span class="fl">1</span>, VALORACION <span class="op">=</span> <span class="fl">3</span>, <span class="st">" "</span> <span class="op">=</span> <span class="fl">1</span><span class="op">)</span>,</span>
<span>                   bold<span class="op">=</span><span class="cn">T</span>,</span>
<span>                   line<span class="op">=</span><span class="cn">T</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/row_spec.html">row_spec</a></span><span class="op">(</span><span class="fl">0</span>, bold<span class="op">=</span> <span class="cn">T</span>, align <span class="op">=</span> <span class="st">"c"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/column_spec.html">column_spec</a></span><span class="op">(</span><span class="fl">1</span>, bold <span class="op">=</span> <span class="cn">T</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class="table table-striped" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-301">Table 10.1: </span><span id="tab:unnamed-chunk-301">Table 10.2: </span>Empresas eólicas
</caption>
<thead>
<tr>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; " colspan="1">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
DIMENSION
</div>
</th>
<th style="border-bottom:hidden;padding-bottom:0; padding-left:3px;padding-right:3px;text-align: center; font-weight: bold; " colspan="3">
<div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
VALORACION
</div>
</th>
<th style="empty-cells: hide;border-bottom:hidden;" colspan="1">
</th>
</tr>
<tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
NORMAL
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
OPTIMA
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
PESIMA
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Sum
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;font-weight: bold;">
GRANDE
</td>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
19
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
MEDIA
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
10
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
REDUCIDA
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
22
</td>
</tr>
<tr>
<td style="text-align:left;font-weight: bold;">
Sum
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
51
</td>
</tr>
</tbody>
</table></div>
<p>Es de destacar que, en el código de la tabla, se ha añadido la función <code>addmargin()</code> para que se añadan las frecuencias marginales de las categorias de ambos atributos (sumas de filas y columnas). Además, se ha utilizado la función <code><a href="https://rdrr.io/pkg/kableExtra/man/add_header_above.html">add_header_above()</a></code> del paquete <a href="http://haozhu233.github.io/kableExtra/">kableExtra</a> para añadir filas superiores al encabezado, que ocupen distintas cantidades de columnas.</p>
<p>La tabla también se puede representar gráficamente mediante la función <code><a href="https://rdrr.io/pkg/vcd/man/mosaic.html">mosaic()</a></code> de la librería <code>{vcd}</code>, con lo que se percibirá mejor la magnitud de las frecuencias conjuntas (celdas de la tabla). A mayor frecuencia, mayor área del rectángulo correspondiente:</p>
<div class="sourceCode" id="cb364"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va">vcd</span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/vcd/man/mosaic.html">mosaic</a></span><span class="op">(</span><span class="va">tab.originales</span>,</span>
<span>           main <span class="op">=</span> <span class="st">"Eólicas: Dimensión Matriz y Valoración Expertos."</span>,</span>
<span>           shade <span class="op">=</span> <span class="cn">T</span>,</span>
<span>           gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/vcd/man/shadings.html">shading_Marimekko</a></span><span class="op">(</span><span class="va">tab.originales</span><span class="op">)</span>,</span>
<span>           main_gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fontsize <span class="op">=</span> <span class="fl">14</span><span class="op">)</span>,</span>
<span>           sub_gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fontsize <span class="op">=</span> <span class="fl">12</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-302-1.png" width="672"></div>
<p>Los argumentos de la función <code><a href="https://rdrr.io/pkg/vcd/man/mosaic.html">mosaic()</a></code> juegan el siguiente papel:</p>
<ol style="list-style-type: decimal">
<li><p><strong><code>tab.originales</code></strong>: Es la tabla de contingencia que contiene los datos a visualizar en el gráfico mosaico. Debe ser una tabla de contingencia creada con la función <code><a href="https://rdrr.io/r/base/table.html">table()</a></code> o una matriz con datos categóricos.</p></li>
<li><p><strong><code>main</code></strong>: Título principal del gráfico.</p></li>
<li><p><strong><code>shade</code></strong>: Si se establece en <code>TRUE</code>, aplica un coloreado a las celdas del mosaico; si es <code>FALSE</code> todas los rectángulos serán del mismo color.</p></li>
<li><p><strong><code>gp</code></strong>: Parámetros gráficos para personalizar la apariencia del gráfico. En este caso, se usa <code><a href="https://rdrr.io/pkg/vcd/man/shadings.html">shading_Marimekko()</a></code> para aplicar un sombreado específico. Hay otras funciones de parámetros gráficos como <code><a href="https://rdrr.io/pkg/vcd/man/shadings.html">shading_hcl()</a></code>, <code>shading_max</code>, o cualquier función personalizada que devuelva un objeto de clase <code>gpar</code>.</p></li>
<li><p><strong><code>main_gp</code></strong>: Parámetros gráficos para el título principal, como el tamaño de la fuente. Se pueden especificar atributos como, por medio de la función <code><a href="https://rdrr.io/r/grid/gpar.html">gpar()</a></code>, como <code>fontsize</code>, <code>fontfamily</code>, <code>col</code>, etc.</p></li>
<li><p><strong><code>sub_gp</code></strong>: Igual que el caso anterior; pero para el subtítulo del gráfico de mosaico.</p></li>
</ol>
<p>En nuestro ejemplo, podemos apreciar con claridad como una importante proporción de los casos (empresas) se concentran en la combinación de valoración óptima y dimensión de la empresa matriz reducida. También es destacable la combinación de valoración normal y dimensión de la compañía matriz grande. Por el lado opuesto, destaca la combinación de valoración normal y dimensión de la matriz media, que no posee ningún caso (frecuencia 0), y valoración pésima y dimesión de la matriz reducida.</p>
<p>Otro modo de visualizar la estructura de la tabla es hacer gráficos de barras que muestren las frecuencias de las categorías de cada factor (frecuencias marginales), aunque en cada barra se pueda diferenciar, además, los casos o frecuencias que pertenecen a las categorías del otro factor. En nuestro caso:</p>
<div class="sourceCode" id="cb365"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="co"># Representando frecuencias de categorias en factores</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span></span>
<span>    <span class="va">g1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">originales</span>, mapping<span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span> <span class="va">DIMENSION</span>, fill <span class="op">=</span> <span class="va">VALORACION</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>          <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>          <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Tamaño de la matriz."</span>, subtitle <span class="op">=</span> <span class="st">"Empresas eólicas"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>          <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Frecuencias"</span><span class="op">)</span> <span class="op">+</span></span>
<span>          <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Dimensión"</span><span class="op">)</span></span>
<span></span>
<span>    <span class="va">g2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">originales</span>, mapping<span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span> <span class="va">VALORACION</span>, fill <span class="op">=</span> <span class="va">DIMENSION</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>          <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>          <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Valoración Expertos"</span>, subtitle <span class="op">=</span> <span class="st">"Empresas eólicas"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>          <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Frecuencias"</span><span class="op">)</span> <span class="op">+</span></span>
<span>          <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Valoración"</span><span class="op">)</span></span>
<span></span>
<span>    <span class="op">(</span><span class="va">g1</span> <span class="op">+</span> <span class="va">g2</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_annotation.html">plot_annotation</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Frecuencias Marginales."</span>,</span>
<span>                  theme <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-303-1.png" width="672"></div>
<p>Se observa cómo, en cuanto al atributo o factor DIMENSION, la categoría más frecuente es la dimensión “REDUCIDA”, mientras que la categoría que menos se da en la muestra es, destacadamente, “MEDIA”. Además, como ya se ha comentado, destaca que la mayor parte de los casos de la categoría “REDUCIDA” tienen una valoración de “OPTIMA” en el factor VALORACION. También llama la atención que en la categoría “MEDIA” no existen casos con valoración “NORMAL”. En cuanto al gráfico del atributo o factor “VALORACION”, el mayor número de frecuencias, de modo muy destacado, se concentran en la categoría “OPTIMA”, estando las otras dos categorías bastante igualadas en cuanto al número de casos. Es reseñable también que, en la categoría “OPTIMA”, la mayor parte de casos tienen una dimensión “REDUCIDA”.</p>
<p>Como ya hemos dicho, una de las cuestiones más importantes en el análisis de tablas de contingencia es <strong>determinar si existe asociación entre ambos atributos o factores</strong> (valoración de las empresas y dimensión de las compañías matrices), en el sentido de poder plantear que los casos (empresas) concentradas en ciertas categorías concretas de uno de los factores o atributos tienden a concentrarse, simultáneamente, en ciertas categorías concretas del otro factor o atributo; o al revés: que el hecho de que los casos no tiendan a concentrarse en ciertas categorías de uno de los factores o atributos está relacionado con que no se concentren en ciertas categorías del otro factor o atributo. En nuestro ejemplo, ya hemos señalado algunas combinaciones de categorías que podrían llevar a pensar a que existe cierto grado de asociación entre los atributos DIMENSION y VALORACION.</p>
<p>Existen diferentes pruebas para verificar la posible existencia de asociación entre dos factores. Una de ellas es el <em><strong>contraste o prueba de asociación de Pearson</strong>.</em> Este contraste se base en un estadístico del contraste, que bajo la hipótesis nula de que no existe asociación sigue una distribución Chi/Ji Cuadrado. El estadístico, en realidad, es una medida global de <strong>lo distante que está la tabla de contingencia observada (sus frecuencias conjuntas) respecto a la estructura “ideal” que tendría que tener si existiera independencia</strong> “total” entre ambos atributos. Así, el estadístico del contraste de la <em>prueba de asociación de Pearson</em> es:</p>
<p><span class="math display">\[
\chi^2 = \sum_{i=1}^{r} \sum_{j=1}^{c} \frac{(O_{ij} - E_{ij})^2}{E_{ij}}
\]</span></p>
<p>donde:</p>
<ul>
<li><p>( <span class="math inline">\(O_{ij}\)</span> ) es la frecuencia observada en la celda ( (i, j) ).</p></li>
<li><p>( <span class="math inline">\(E_{ij}\)</span> ) es la frecuencia esperada en la celda ( (i, j) ), calculada como ( <span class="math inline">\(E_{ij} = \frac{R_i \cdot C_j}{N}\)</span> ).</p></li>
<li><p>( <span class="math inline">\(R_i\)</span> ) es el total de la fila ( i ).</p></li>
<li><p>( <span class="math inline">\(C_j\)</span> ) es el total de la columna ( j ).</p></li>
<li><p>( <span class="math inline">\(N\)</span> ) es el total general de todas las observaciones.</p></li>
</ul>
<p>Los <em>residuos estandarizados</em> son una medida de la desviación de las frecuencias observadas respecto a las frecuencias teóricas o esperadas (en caso de independencia perfecta entre atributos) en una tabla de contingencia. Se utilizan para identificar celdas que contribuyen significativamente a la asociación entre las variables. La fórmula para calcular los residuos estandarizados es:</p>
<p><span class="math display">\[
 r_{ij} = \frac{O_{ij} - E_{ij}}{\sqrt{E_{ij} \left(1 - \frac{R_i}{N}\right) \left(1 - \frac{C_j}{N}\right)}}
\]</span></p>
<p>donde:</p>
<ul>
<li>( <span class="math inline">\(r_{ij}\)</span> ) es el residuo estandarizado para la celda en la fila ( i ) y la columna ( j ).</li>
</ul>
<p>El paquete <code>{stats}</code> de R (que se carga automáticamente, por defecto, al iniciar R, por lo que no hay que “activarlo”), contiene la función <code><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test()</a></code> que efectúa la prueba de asociación de <em>Pearson</em>. El código y resultado de la prueba es:</p>
<div class="sourceCode" id="cb366"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># INDEPENDENCIA / ASOCIACION</span></span>
<span>  </span>
<span>  <span class="co"># Test de asociación de Pearson (Ji-Cuadrado)</span></span>
<span>    </span>
<span>  <span class="va">Prueba_asoc_Pearson</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/chisq.test.html">chisq.test</a></span><span class="op">(</span><span class="va">tab.originales</span><span class="op">)</span></span>
<span>  <span class="va">Prueba_asoc_Pearson</span></span></code></pre></div>
<pre><code>## 
##  Pearson's Chi-squared test
## 
## data:  tab.originales
## X-squared = 11.494, df = 4, p-value = 0.02154</code></pre>
<p>En nuestro caso, el <em>p-valor</em> es menor que 0,05, luego <strong>se rechaza la hipótesis nula de independencia</strong> de los atributos o factores, y admitimos que <strong>existe asociación entre ambos.</strong></p>
<p>Precisamente, el paquete <code>{vcd}</code> ofrece la posibilidad de, para cada frecuencia conjunta, visualizar la diferencia estandarizada entre el valor observado y el que debería darse en el caso de que existiera independencia perfecta entre los dos atributos o factores (<em>residuo de Pearson</em>). Para ello, se aplica la función <code><a href="https://rdrr.io/pkg/vcd/man/assoc.html">assoc()</a></code>, destinada a construir un gráfico con los residuos de <em>Pearson</em> de la tabla de contingencia. Los residuos, si son estadísticamente significativos para una significación de 0,05, se colorean de naranja, y en caso contrario de gris. Para determinar los colores concretos, se ha creado la función <code>custom_shading()</code>, que se pasa en el argumento <code>gp=</code> para personalizar el color concreto de cada barra del gráfico:</p>
<div class="sourceCode" id="cb368"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="va">Residuos_std</span> <span class="op">&lt;-</span> <span class="va">Prueba_asoc_Pearson</span><span class="op">$</span><span class="va">stdres</span></span>
<span></span>
<span>  <span class="co"># Definir una función de sombreado personalizada</span></span>
<span>  <span class="va">custom_shading</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">residuals</span>, <span class="va">cutoff</span> <span class="op">=</span> <span class="fl">1.96</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="co"># Crear una matriz de colores basada en los residuos estandarizados</span></span>
<span>    <span class="va">colors</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/ifelse.html">ifelse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/MathFun.html">abs</a></span><span class="op">(</span><span class="va">residuals</span><span class="op">)</span> <span class="op">&gt;</span> <span class="va">cutoff</span>, <span class="st">"orange"</span>, <span class="st">"lightgray"</span><span class="op">)</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">colors</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span>  </span>
<span>  <span class="co"># Aplicar la función de sombreado en el gráfico mosaico</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://rdrr.io/pkg/vcd/man/assoc.html">assoc</a></span><span class="op">(</span><span class="va">tab.originales</span>,</span>
<span>        main <span class="op">=</span> <span class="st">"Asociación: Dimensión Matriz y Valoración Expertos."</span>,</span>
<span>        sub <span class="op">=</span> <span class="st">"Residuos de Pearson Tipificados. Naranja: significativos con sig. = 0,05"</span>,</span>
<span>        compress <span class="op">=</span> <span class="cn">FALSE</span>,</span>
<span>        gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fill <span class="op">=</span> <span class="fu">custom_shading</span><span class="op">(</span><span class="va">Residuos_std</span><span class="op">)</span><span class="op">)</span>,</span>
<span>        main_gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fontsize <span class="op">=</span> <span class="fl">14</span><span class="op">)</span>,</span>
<span>        sub_gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fontsize <span class="op">=</span> <span class="fl">12</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-305-1.png" width="672"></div>
<p>Puede observarse cómo en las combinaciones GRANDE/NORMAL, GRANDE/OPTIMA y MEDIA/NORMAL los residuos de Pearson son estadísticamente significativos (lo que, a su vez, indica que las frecuencias correspondientes están muy alejadas de las que debería haber en caso de independencia perfecta), lo que llevaría que la prueba haya rechazado la hipótesis de independencia entre los atributos o factores.</p>
</div>
<div id="análisis-de-correspondencias." class="section level2" number="10.3">
<h2>
<span class="header-section-number">10.3</span> Análisis de correspondencias.<a class="anchor" aria-label="anchor" href="#an%C3%A1lisis-de-correspondencias."><i class="fas fa-link"></i></a>
</h2>
<p>El <em>análisis de correspondencias</em> es una técnica destinada a <strong>representar visualmente una tabla de contingencia, en un gráfico bidimensional</strong>. Puede utilizarse para representar una tabla de dos atributos o factores (análisis de correspondencias simple) o de más de dos (análisis de correspondencias múltiple). Cuando en el gráfico bidimensional se representan más de dos atributos o factores, este análisis de convierte, además, en una <strong>técnica de reducción de la dimensión de la información.</strong> De hecho, se puede afirmar que el análisis de correspondencias es una suerte de análisis de <strong>componentes principales aplicado a variables categóricas</strong>.</p>
<p>De acuerdo a lo anterior, se pueden establecer los siguientes paralelismos:</p>
<ul>
<li><p>Las componentes en el análisis de componentes principales equivalen a los <strong>ejes o dimensiones</strong> del análisis de correspondencias.</p></li>
<li><p>La varianza total o <em>comunalidad</em> de las variables originales métricas del análisis de componentes principales pasa a ser, en el análisis de correspondencias, la <strong>inercia total</strong>.</p></li>
<li><p>La varianza que es capaz de asumir cada componente en el análisis de componentes principales ahora se denomina <strong>inercia principal</strong> (del eje o dimensión en cuestión).</p></li>
<li><p>Las puntuaciones de las componentes para un caso son, ahora, las <strong>coordenadas</strong> de una categoría de uno de los atributos o factores.</p></li>
<li><p>El papel de las cargas de las variables en las componentes principales lo asumen las <strong>contribuciones</strong> de las categorías o niveles de los factores o atributos en los ejes o dimensiones.</p></li>
</ul>
<p>Como principal resultado del análisis se obtendrá un gráfico de dos ejes (dimensiones) en el cuál <strong>se situarán más próximas las categorías de uno y otro factor que mantengan entre sí cierta tendencia a asociarse</strong>.</p>
<p>Existen varios paquetes de R que permiten desarrollar un análisis de correspondencias simple (de dos atributos o factores), como es nuestro ejemplo. Hemos optado, en el ejemplo, por utilizar el paquete <a href="http://factominer.free.fr">FactoMineR</a>. Este paquete dispone de la función <code><a href="https://rdrr.io/pkg/FactoMineR/man/CA.html">CA()</a></code>, que es la encargada de realizar los cálculos del análisis.</p>
<p>En el siguiente código, el análisis de correspondencias se aplica a la tabla de contingencia “tab.originales”, almacenándose la solución en la lista “aceolicas”. Luego, se crea la lista “SolucionCA” para almacenar las tres tablas que recogerán los resultados. Después se crea un <em>data frame</em>, “EigenCA”, con el elemento “eig” de la solución del análisis. Ese elemento es un <em>data frame</em> de dos columnas (dimensiones o ejes del análisis), para cada una de las cuales se reúnen tres informaciones: la inercia principal o varianza recogida por la dimensión o eje, el porcentaje que supone respecto a la inercia total puesta en juego, y el porcentaje acumulado. El <em>data frame</em> se pasa a formato “tabla” de <code><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable()</a></code> con el nombre “TableEigenCA”, que se guarda en la lista “SolucionCA” como su primer elemento.</p>
<p>Después se generan dos tablas con los mismos elementos, para cada uno de los atributos o factores del análisis. La primera corresponde al atributo DIMENSION. Esta tabla cuenta con una fila por cada una de las categorías de DIMENSION, esto es, “GRANDE”, “MEDIA” y “REDUCIDA”. La segunda corresponde al atributo VALORACION, y cuenta con una fila para sus categorías, “OPTIMA”, “NORMAL”, “PESIMA”. En ambas tablas, las columnas son las siguientes:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Inercia</strong>: La inercia es una medida de la varianza explicada por cada fila o columna (categoría de alguno de los atributos) en el análisis de correspondencias. Valores más altos indican que la fila o columna contribuye más a la varianza total del análisis (Inercia Total).</p></li>
<li><p><strong>Coordenadas Dim. 1 y Dim. 2</strong>: Coordenadas de las filas o columnas en las dos dimensiones del espacio de correspondencias. Indican la posición de cada fila o columna en el espacio bidimensional.</p></li>
<li><p><strong>cos2 Dim. 1 y Dim. 2 (Coseno Cuadrado)</strong>: El coseno cuadrado de los ángulos entre las filas o columnas y las dimensiones. Mide la calidad de la representación de las filas o columnas en las dimensiones. Valores cercanos a 1 indican que la fila o columna está bien representada en esa dimensión. Valores bajos indican una mala representación.</p></li>
</ol>
<div class="sourceCode" id="cb369"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># ANALISIS DE CORRESPONDENCIAS SIMPLE</span></span>
<span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="http://factominer.free.fr">FactoMineR</a></span><span class="op">)</span></span>
<span>  <span class="va">aceolicas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/FactoMineR/man/CA.html">CA</a></span><span class="op">(</span>X <span class="op">=</span> <span class="va">tab.originales</span>, graph <span class="op">=</span> <span class="cn">F</span><span class="op">)</span></span>
<span></span>
<span>  <span class="va">SolucionCA</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="va">EigenCA</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/as.data.frame.html">as.data.frame</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/t.html">t</a></span><span class="op">(</span><span class="va">aceolicas</span><span class="op">$</span><span class="va">eig</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">EigenCA</span><span class="op">$</span><span class="va">elemento</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Inercia Total"</span>, <span class="st">"% Inercia Principal"</span>, <span class="st">"Acumulada"</span><span class="op">)</span></span>
<span>  <span class="va">EigenCA</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">EigenCA</span>, row.names <span class="op">=</span> <span class="fl">3</span><span class="op">)</span></span>
<span>  </span>
<span>  </span>
<span>  <span class="va">TableEigenCA</span> <span class="op">&lt;-</span> <span class="va">EigenCA</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>format <span class="op">=</span> <span class="va">knitr.table.format</span>,</span>
<span>          caption<span class="op">=</span><span class="st">"Análisis de correspondencias: Dimensión Matrix vs Valoración."</span>,</span>
<span>          col.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Dimensión/Eje 1"</span>, <span class="st">"Dimensión/Eje 2"</span><span class="op">)</span>,</span>
<span>          digits <span class="op">=</span> <span class="fl">3</span>,</span>
<span>          align<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"c"</span>, <span class="st">"c"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>full_width <span class="op">=</span> <span class="cn">F</span>,</span>
<span>                  bootstrap_options <span class="op">=</span> <span class="st">"striped"</span>, <span class="st">"bordered"</span>, <span class="st">"condensed"</span>,</span>
<span>                  position <span class="op">=</span> <span class="st">"center"</span>,</span>
<span>                  font_size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/row_spec.html">row_spec</a></span><span class="op">(</span><span class="fl">0</span>, bold<span class="op">=</span> <span class="cn">T</span>, align <span class="op">=</span> <span class="st">"c"</span><span class="op">)</span></span>
<span>  </span>
<span>    <span class="va">SolucionCA</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span><span class="va">TableEigenCA</span></span>
<span>  </span>
<span>  <span class="co"># Extraer la información de las filas</span></span>
<span>    <span class="va">rows_data</span> <span class="op">&lt;-</span> <span class="va">aceolicas</span><span class="op">$</span><span class="va">row</span><span class="op">$</span><span class="va">coord</span></span>
<span>    <span class="va">rows_cos2</span> <span class="op">&lt;-</span> <span class="va">aceolicas</span><span class="op">$</span><span class="va">row</span><span class="op">$</span><span class="va">cos2</span></span>
<span></span>
<span>  <span class="co"># Crear un DataFrame para las filas</span></span>
<span>    <span class="va">rows_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>    Iner_1000 <span class="op">=</span> <span class="va">aceolicas</span><span class="op">$</span><span class="va">row</span><span class="op">$</span><span class="va">inertia</span>,</span>
<span>    Dim_1 <span class="op">=</span> <span class="va">rows_data</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>,</span>
<span>    cos2_1 <span class="op">=</span> <span class="va">rows_cos2</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>,</span>
<span>    Dim_2 <span class="op">=</span> <span class="va">rows_data</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span>,</span>
<span>    cos2_2 <span class="op">=</span> <span class="va">rows_cos2</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span></span>
<span>    <span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">rows_df</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">rows_data</span><span class="op">)</span></span>
<span>    </span>
<span>    <span class="va">TableRows</span> <span class="op">&lt;-</span> <span class="va">rows_df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>      <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>format <span class="op">=</span> <span class="va">knitr.table.format</span>,</span>
<span>          caption<span class="op">=</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"Análisis de correspondencias: "</span>, <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">originales</span><span class="op">)</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span>, <span class="st">"."</span><span class="op">)</span><span class="op">)</span>,</span>
<span>          col.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Inercia"</span>, <span class="st">"Coordenadas Dim. 1"</span>, <span class="st">"Cos2 Dim. 1"</span>,</span>
<span>                        <span class="st">"Coordenadas Dim. 2"</span>, <span class="st">"Cos2 Dim. 2"</span><span class="op">)</span>,</span>
<span>          digits <span class="op">=</span> <span class="fl">3</span>,</span>
<span>          align<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"c"</span>, <span class="st">"c"</span>, <span class="st">"c"</span>, <span class="st">"c"</span>, <span class="st">"c"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>full_width <span class="op">=</span> <span class="cn">F</span>,</span>
<span>                  bootstrap_options <span class="op">=</span> <span class="st">"striped"</span>, <span class="st">"bordered"</span>, <span class="st">"condensed"</span>,</span>
<span>                  position <span class="op">=</span> <span class="st">"center"</span>,</span>
<span>                  font_size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/row_spec.html">row_spec</a></span><span class="op">(</span><span class="fl">0</span>, bold<span class="op">=</span> <span class="cn">T</span>, align <span class="op">=</span> <span class="st">"c"</span><span class="op">)</span></span>
<span>    </span>
<span>    <span class="va">SolucionCA</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span><span class="va">TableRows</span></span>
<span></span>
<span>  <span class="co"># Extraer la información de las columnas</span></span>
<span>    <span class="va">columns_data</span> <span class="op">&lt;-</span> <span class="va">aceolicas</span><span class="op">$</span><span class="va">col</span><span class="op">$</span><span class="va">coord</span></span>
<span>    <span class="va">columns_cos2</span> <span class="op">&lt;-</span> <span class="va">aceolicas</span><span class="op">$</span><span class="va">col</span><span class="op">$</span><span class="va">cos2</span></span>
<span></span>
<span>  <span class="co"># Crear un DataFrame para las columnas</span></span>
<span>    <span class="va">columns_df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>    Inercia <span class="op">=</span> <span class="va">aceolicas</span><span class="op">$</span><span class="va">col</span><span class="op">$</span><span class="va">inertia</span>,</span>
<span>    Dim_1 <span class="op">=</span> <span class="va">columns_data</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>,</span>
<span>    cos2_1 <span class="op">=</span> <span class="va">columns_cos2</span><span class="op">[</span>, <span class="fl">1</span><span class="op">]</span>,</span>
<span>    Dim_2 <span class="op">=</span> <span class="va">columns_data</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span>,</span>
<span>    cos2_2 <span class="op">=</span> <span class="va">columns_cos2</span><span class="op">[</span>, <span class="fl">2</span><span class="op">]</span></span>
<span>    <span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">columns_df</span><span class="op">)</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">columns_data</span><span class="op">)</span></span>
<span></span>
<span>    <span class="va">TableCols</span> <span class="op">&lt;-</span> <span class="va">columns_df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>      <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>format <span class="op">=</span> <span class="va">knitr.table.format</span>,</span>
<span>          caption<span class="op">=</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"Análisis de correspondencias: "</span>, <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">originales</span><span class="op">)</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span>, <span class="st">"."</span><span class="op">)</span><span class="op">)</span>,</span>
<span>          col.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Inercia"</span>, <span class="st">"Coordenadas Dim. 1"</span>, <span class="st">"Cos2 Dim. 1"</span>,</span>
<span>                        <span class="st">"Coordenadas Dim. 2"</span>, <span class="st">"Cos2 Dim. 2"</span><span class="op">)</span>,</span>
<span>          digits <span class="op">=</span> <span class="fl">3</span>,</span>
<span>          align<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"c"</span>, <span class="st">"c"</span>, <span class="st">"c"</span>, <span class="st">"c"</span>, <span class="st">"c"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>full_width <span class="op">=</span> <span class="cn">F</span>,</span>
<span>                  bootstrap_options <span class="op">=</span> <span class="st">"striped"</span>, <span class="st">"bordered"</span>, <span class="st">"condensed"</span>,</span>
<span>                  position <span class="op">=</span> <span class="st">"center"</span>,</span>
<span>                  font_size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/row_spec.html">row_spec</a></span><span class="op">(</span><span class="fl">0</span>, bold<span class="op">=</span> <span class="cn">T</span>, align <span class="op">=</span> <span class="st">"c"</span><span class="op">)</span></span>
<span>    </span>
<span>   <span class="va">SolucionCA</span><span class="op">[[</span><span class="fl">3</span><span class="op">]</span><span class="op">]</span> <span class="op">&lt;-</span><span class="va">TableCols</span></span>
<span>   </span>
<span>  <span class="va">SolucionCA</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span></span>
<span>  <span class="va">SolucionCA</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span></span>
<span>  <span class="va">SolucionCA</span><span class="op">[[</span><span class="fl">3</span><span class="op">]</span><span class="op">]</span></span></code></pre></div>
<div class="inline-table"><table class="table table-striped" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-307">Table 10.3: </span><span id="tab:unnamed-chunk-307">Table 10.4: </span>Análisis de correspondencias: Dimensión Matrix vs Valoración.
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Dimensión/Eje 1
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Dimensión/Eje 2
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Inercia Total
</td>
<td style="text-align:center;">
0.175
</td>
<td style="text-align:center;">
0.051
</td>
</tr>
<tr>
<td style="text-align:left;">
% Inercia Principal
</td>
<td style="text-align:center;">
77.514
</td>
<td style="text-align:center;">
22.486
</td>
</tr>
<tr>
<td style="text-align:left;">
Acumulada
</td>
<td style="text-align:center;">
77.514
</td>
<td style="text-align:center;">
100.000
</td>
</tr>
</tbody>
</table></div>
<div class="inline-table"><table class="table table-striped" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-307">Table 10.3: </span><span id="tab:unnamed-chunk-307">Table 10.3: </span>Análisis de correspondencias: DIMENSION.
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Inercia
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Coordenadas Dim. 1
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Cos2 Dim. 1
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Coordenadas Dim. 2
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Cos2 Dim. 2
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
GRANDE
</td>
<td style="text-align:center;">
0.102
</td>
<td style="text-align:center;">
0.516
</td>
<td style="text-align:center;">
0.970
</td>
<td style="text-align:center;">
0.091
</td>
<td style="text-align:center;">
0.030
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA
</td>
<td style="text-align:center;">
0.083
</td>
<td style="text-align:center;">
-0.549
</td>
<td style="text-align:center;">
0.715
</td>
<td style="text-align:center;">
0.347
</td>
<td style="text-align:center;">
0.285
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA
</td>
<td style="text-align:center;">
0.041
</td>
<td style="text-align:center;">
-0.196
</td>
<td style="text-align:center;">
0.408
</td>
<td style="text-align:center;">
-0.236
</td>
<td style="text-align:center;">
0.592
</td>
</tr>
</tbody>
</table></div>
<div class="inline-table"><table class="table table-striped" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-307">Table 10.3: </span>Análisis de correspondencias: VALORACION.
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Inercia
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Coordenadas Dim. 1
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Cos2 Dim. 1
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Coordenadas Dim. 2
</th>
<th style="text-align:center;font-weight: bold;text-align: center;">
Cos2 Dim. 2
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
NORMAL
</td>
<td style="text-align:center;">
0.129
</td>
<td style="text-align:center;">
0.710
</td>
<td style="text-align:center;">
0.996
</td>
<td style="text-align:center;">
-0.044
</td>
<td style="text-align:center;">
0.004
</td>
</tr>
<tr>
<td style="text-align:left;">
OPTIMA
</td>
<td style="text-align:center;">
0.053
</td>
<td style="text-align:center;">
-0.278
</td>
<td style="text-align:center;">
0.773
</td>
<td style="text-align:center;">
-0.150
</td>
<td style="text-align:center;">
0.227
</td>
</tr>
<tr>
<td style="text-align:left;">
PESIMA
</td>
<td style="text-align:center;">
0.044
</td>
<td style="text-align:center;">
-0.157
</td>
<td style="text-align:center;">
0.122
</td>
<td style="text-align:center;">
0.421
</td>
<td style="text-align:center;">
0.878
</td>
</tr>
</tbody>
</table></div>
<p>En nuestro ejemplo, la primera tabla nos informa, esencialmente, de que la primera dimensión o eje recoge el 77,5% de la inercia total (varianza o comportamiento) de las categorías de los dos atributos o factores, mientras que la segunda dimensión o eje asume algo menos del 22,5%. Recordemos que esta interpretación es similar a la que se hace cuando se determinan los porcentajes de “comunalidad” que recogen las componentes calculadas, en el análisis de componentes principales. Recordemos también que, en el caso del análisis de correspondencias simple (dos atributos o factores), las dos dimensiones recogen el 100% de la inercia total (puesto que no se “descarta” ninguna dimensión de las calculadas).</p>
<p>Es habitual que los porcentajes de inercia principal asumidos por ambas dimensiones o ejes puedan estar bastante desequilibrados a favor del primer eje; sobre todo cuando hay una fuerte asociación entre los atributos o factores. Algunas características que pueden ayudar a un mayor equilibrio son:</p>
<ul>
<li><p>Distribución de los Datos: Una distribución equilibrada de las frecuencias en la tabla de contingencia puede ayudar a que la inercia total se distribuya de manera más uniforme.</p></li>
<li><p>Número de Categorías: Tener un número similar de categorías en ambos atributos puede favorecer una distribución más equitativa de la inercia entre los ejes.</p></li>
<li><p>Relaciones Simétricas: Que las relaciones entre las categorías de los atributos sean simétricas y no estén dominadas por unas pocas asociaciones fuertes (ninguna valoración domina de un modo extraordinario en alguna dimensión de matriz).</p></li>
<li><p>Tamaño de la Muestra: Un tamaño de muestra grande.</p></li>
<li><p>Homogeneidad de las Categorías: Que las categorías dentro de cada atributo sean relativamente homogéneas respecto a sus asociaciones con las categorías del otro atributo (la estructura de valoraciones es similar entre dimensiones).</p></li>
</ul>
<p>En cuanto a la segunda tabla, destinada al análisis de las categorías del atributo o factor DIMENSION, podemos concluir lo siguiente: la mayor varianza (inercia) de las tres categorías de dimensión de la compañía matriz de pertenencia corresponde a “GRANDE”, seguida de “MEDIA” y “REDUCIDA”. En cuanto a la calidad de la representación de estas categorías en las dos dimensiones o ejes; las categorías “GRANDE” y “MEDIA” están representadas principalmente por la dimensión o eje 1; solo la categoría “REDUCIDA” viene mejor representada (levemente) por la dimensión o eje 2.</p>
<p>Por último, la tercera tabla recoge la representación de las categorías del atributo o factor VALORACION: “OPTIMA”, “NORMAL” y “PESIMA”. La mayor inercia o varianza es la de “NORMAL”, seguida de “OPTIMA” y, por último, “PESIMA”. En cuanto a la calidad de la representación en las dimensiones o ejes, “NORMAL” y “OPTIMA” vienen representadas, casi exclusivamente, por la dimensión o eje 1; mientras que ocurre lo contrario con la categoría “PESIMA”.</p>
<p>El principal output del análisis de correspondencias es el gráfico bidimensional donde se representan las categorías de los atributos o factores. En general, cuanto más cerca se localicen determinada categoría de un factor y determinada categoría del otro, mayor será la relación estadística (asociación) entre ambas categorías, lo que implica a su vez mayor asociación entre los atributos o factores.</p>
<p>Antes de presentar el gráfico bidimensional, vamos a construir un gráfico de barras con los porcentajes de la inercia total que asumen cada una de las dos dimenciones o ejes del gráfico. Esto es importante, ya que si la inercia recogida por la segunda dimensión o eje es muy pequeña, como a veces ocurre, habría que tener en cuenta, sobre todo, la localización de las categorías en la primera dimensión o eje, a la hora de establecer conclusiones en cuanto a la asociación o no entre categorías. También es necesario tener en cuenta la calidad con que cada eje representa a cada categoría de cada variable o factor, medida con el coseno cuadrado (cos2), como ya se ha comentado.</p>
<p>Para crear de un modo sencillo el gráfico de contribuciones de los ejes o dimensiones a la inercia total, puede recurrirse a la función <code><a href="https://rdrr.io/pkg/factoextra/man/eigenvalue.html">fviz_screeplot()</a></code> del paquete <a href="http://www.sthda.com/english/rpkgs/factoextra">factoextra</a>:</p>
<div class="sourceCode" id="cb370"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="co"># Gráfico de contribuciones de las dimensiones  a la Inercia Total</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://www.sthda.com/english/rpkgs/factoextra">factoextra</a></span><span class="op">)</span></span>
<span></span>
<span>    <span class="va">gcontrib</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/factoextra/man/eigenvalue.html">fviz_screeplot</a></span><span class="op">(</span><span class="va">aceolicas</span>,</span>
<span>                               addlabels<span class="op">=</span> <span class="cn">TRUE</span>,</span>
<span>                               barcolor<span class="op">=</span> <span class="st">"darkblue"</span>,</span>
<span>                               barfill<span class="op">=</span> <span class="st">"orange"</span>,</span>
<span>                               linecolor<span class="op">=</span> <span class="st">"red"</span><span class="op">)</span> <span class="op">+</span></span>
<span>                <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title<span class="op">=</span> <span class="st">"Contribución de los ejes a la Inercia Total."</span>,</span>
<span>                     subtitle <span class="op">=</span> <span class="st">"Dimensión Matriz y Valoración Expertos."</span><span class="op">)</span> <span class="op">+</span></span>
<span>                <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Porcentaje de Inercia Total"</span><span class="op">)</span> <span class="op">+</span></span>
<span>                <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Eje"</span><span class="op">)</span> <span class="op">+</span></span>
<span>                <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>text <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">gcontrib</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-308-1.png" width="672"></div>
<p>Puede observarse, como ya se recogió en la primera table de la solución, que la primera dimensión o eje asume el 77,5% de la inercia tital (varianza o comportamiento de las categorías), mientras que la segunda dimensión o eje asume el 22,5% restante.</p>
<p>En cuanto al gráfico bidimensional, puede obtenerse igualmente mediante la función <code><a href="https://rdrr.io/pkg/factoextra/man/fviz_ca.html">fviz_ca_biplot()</a></code> de <a href="http://www.sthda.com/english/rpkgs/factoextra">factoextra</a>. Este es el papel que juegan los diferentes argumentos de la función:</p>
<ul>
<li><p><strong><code>map = "symmetric"</code></strong>: Representa tanto las filas como las columnas en el mismo espacio, utilizando la misma escala.</p></li>
<li><p><strong><code>axes = c(1, 2)</code></strong>: Selecciona las dos primeras dimensiones para el gráfico.</p></li>
<li><p><strong><code>label = "all"</code></strong>: Muestra las etiquetas de todas las categorías.</p></li>
<li><p><strong><code>repel = TRUE</code></strong>: Evita la superposición de etiquetas.</p></li>
<li><p><strong><code>col.col</code> y <code>col.row</code></strong>: Colores para las columnas y filas, respectivamente.</p></li>
<li><p><strong><code><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs()</a></code></strong>: Añade títulos y subtítulos al gráfico.</p></li>
<li><p><strong><code><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme()</a></code></strong>: Ajusta el tamaño del texto en el gráfico.</p></li>
</ul>
<p>Es de destacar que el argumento <code>map=</code> controla cómo se representan las filas y columnas en el gráfico bidimensional del análisis de correspondencias. Este argumento tiene varias opciones que determinan la escala y la simetría de la representación. Para representar las posibles asociaciones entre las categorías de los dos factores implicados, la opción más apropiada es “symmetric”. Esta opción permite visualizar las filas y las columnas en el mismo espacio, facilitando la interpretación de las asociaciones entre las categorías de ambas variables.</p>
<div class="sourceCode" id="cb371"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">gbiplot</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/factoextra/man/fviz_ca.html">fviz_ca_biplot</a></span> <span class="op">(</span><span class="va">aceolicas</span>,</span>
<span>                               axes<span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>,<span class="fl">2</span><span class="op">)</span>,</span>
<span>                               label<span class="op">=</span> <span class="st">"all"</span>,</span>
<span>                               repel <span class="op">=</span> <span class="cn">T</span>,</span>
<span>                               col.col<span class="op">=</span> <span class="st">"orange"</span>,</span>
<span>                               col.row<span class="op">=</span> <span class="st">"darkblue"</span>,</span>
<span>                               map<span class="op">=</span> <span class="st">"symmetric"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span><span class="op">(</span>title<span class="op">=</span> <span class="st">"Gráfico de dispersión de categorías."</span>,</span>
<span>         subtitle <span class="op">=</span> <span class="st">"Eólicas: Matriz y Valoración Expertos."</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>text <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span>    <span class="va">gbiplot</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-309-1.png" width="672"></div>
<p>En nuestro ejemplo, se aprecia cómo hay una intensa asociación entre la categoría de VALORACIÓN “OPTIMA”, y la categoria de DIMENSION (de la empresa matriz correspondiente) “REDUCIDA”. También se aprecia cierta asociación entre las categorías de DIMENSION “GRANDE” y VALORACION “NORMAL”. Por último la categoría de VALORACION “PESIMA”, y la categoría del factor o atributo DIMENSION “MEDIA” están bastante alejados de otras categorías, lo que implica que parece no estar muy asociadas con otras categorías específicas.</p>
<p>Finalmente, para una presentación más compacta de los dos últimos gráficos, puede recurrirse al paquete {patchwork}:</p>
<div class="sourceCode" id="cb372"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">gcombinado</span> <span class="op">&lt;-</span> <span class="va">gcontrib</span> <span class="op">/</span> <span class="va">gbiplot</span></span>
<span>    <span class="va">gcombinado</span> <span class="op">&lt;-</span> <span class="va">gcombinado</span> <span class="op">+</span></span>
<span>      <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_annotation.html">plot_annotation</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"DIMENSIÓN MATRIZ vs VALORACIÓN EXPERTOS."</span>,</span>
<span>      subtitle <span class="op">=</span> <span class="st">"Empresas eólicas."</span>,</span>
<span>      caption <span class="op">=</span> <span class="st">"Análisis de Correspondencias Simple."</span>,</span>
<span>      theme <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">16</span>, face <span class="op">=</span> <span class="st">"bold"</span><span class="op">)</span>,</span>
<span>                    plot.subtitle <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">14</span><span class="op">)</span>,</span>
<span>                    plot.caption <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span><span class="op">)</span></span>
<span>    <span class="op">)</span></span>
<span></span>
<span>    <span class="va">gcombinado</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-310-1.png" width="672"></div>
</div>
<div id="modelos-logaritmico-lineales-aplicados-a-tablas-de-contingencia." class="section level2" number="10.4">
<h2>
<span class="header-section-number">10.4</span> Modelos logaritmico-lineales aplicados a tablas de contingencia.<a class="anchor" aria-label="anchor" href="#modelos-logaritmico-lineales-aplicados-a-tablas-de-contingencia."><i class="fas fa-link"></i></a>
</h2>
<p>Volviendo a la verificación de la existencia de asociación entre factores, hemos de tener en cuenta la posibilidad de que los factores en estudio sean más de dos. En este caso multifactorial, no son aplicable las técnicas exploradas anteriormente, pensadas para el caso bifactorial (simple).</p>
<p>Una posibilidad que se nos ofrece es la aplicación de modelos logarítmico-lineales (log-lineales) a tablas de contingencia multifactoriales, que es lo que se tratará en este apartado.</p>
<p>Los modelos log-lineales aplicados a tablas de contingencia parten de la condición de independencia entre factores. Supongamos el caso simple, con una tabla de contingencia de dos factores o atributos, A y B. Bajo la hipótesis de independencia (absoluta o teórica) entre los factores, tendremos que cada frecuencia absoluta conjunta de la tabla se obtiene como:</p>
<p><span class="math display">\[
n_{ij} = \frac{R_i \cdot C_j}{N} = N \cdot \frac{R_i}{N} \cdot \frac{C_j}{N}
\]</span> con:</p>
<ul>
<li>( <span class="math inline">\(n_{ij}\)</span> ) es la frecuencia conjunta para la categoría o fila ( i ) del atributo o factor A, y la categoría o columna ( j ) del atributo o factor B).</li>
<li>( <span class="math inline">\(R_i\)</span> ) es el total de la fila ( i ) del atributo o factor A.</li>
<li>( <span class="math inline">\(C_j\)</span> ) es el total de la columna ( j ) del atributo o factor B.</li>
</ul>
<p>Tomando logaritmos:</p>
<p><span class="math display">\[
\ln{n_{ij}} = ln{N} \ + ln{\frac{R_i}{N}} + ln{\frac{C_j}{N}}
\]</span></p>
<p>Y renombrando los términos:</p>
<p><span class="math display">\[
\ln{n_{ij}} = \lambda + \lambda^A_i + \lambda^B_j
\]</span></p>
<p>Si no existe independencia entre ambas variables o factores, tendremos:</p>
<p><span class="math display">\[
\ln{n_{ij}} = \lambda + \lambda^A_i + \lambda^B_j + \lambda^{AB}_{ij}
\]</span></p>
<p>Los términos <span class="math inline">\(\lambda^A_i\)</span> y <span class="math inline">\(\lambda^B_j\)</span> se denominan efectos directos o principales, mientras que el término <span class="math inline">\(\lambda^{AB}_{ij}\)</span> es el efecto conjunto o interacción entre los dos atributos o factores. Bajo la hipótesis de independencia entre los dos factores, ese efecto tomaría valor 0.</p>
<p>Si el modelo planteado solo tiene en la especificación los efectos directos, se dirá que es el <strong>modelo de independencia</strong>. Si se plantean todas las interacciones posibles entre los factores, se hablará del <strong>modelo saturado</strong>. El modelo <em>saturado</em> otorga un ajuste perfecto; pero es poco útil a la hora de extraer conclusiones relevantes. Se requiere un modelo que, aunque no ajuste al 100% las frecuencias, <strong>recoja solo los efectos más importantes</strong>.</p>
<p>Si algunos de los efectos más importantes (es decir, significativos en términos estadísticos) son conjuntos (interacciones), podremos concluir que existe asociación entre los factores del modelo (al menos, entre los que existan interacciones importantes, en el caso de más de dos factores). Si no es así, y el modelo que mejor representa la realidad es el de independencia, diremos que los factores son independientes unos de otros, y que no existe asociación (significativa) entre ellos.</p>
<p>Los modelos han de respetar siempre la regla de la jerarquía en su especificación: solo se podrá plantear en el modelo una interacción entre los atributos A y B si se han especificado los efectos directos de A y de B. O se podrá plantear una interacción conjunta entre los factores A, B y C si se han planteado también las interacciones entre A y B, B y C, y A y C.</p>
<p>Los modelos log-lineales se estiman por el método de máxima-verosimilitud.</p>
<p>La estrategia a seguir para estudiar la asociación entre factores será plantear diferentes especificaciones, y comprobar si son aptas para representar bien la realidad (tabla de contingencia). Eso se consigue mediante pruebas que evalúan la magnitud de los residuos, entendidos como la diferencia entre las frecuencias conjuntas realmente observadas, y las frecuencias estimadas por el modelo estimado. Las dos pruebas más comunes son la del <em>ratio de verosimilitud</em>, y la de <em>Pearson</em>.</p>
<p>SI existen varios modelos que, desde el punto de vista de las pruebas anteriores, son aptos para representarrazonablemente la realidad, se eligirá el mejor de ellos mediante algún criterio específico, como puede ser aquel que minimice el Criterio de Información de Akaike, que penaliza, para una capacidad de explicación semejante, al modelo con una estructura más compleja (más términos).</p>
<p>Los parámetros estimados finalmente, correspondientes a la mejor especificación, informarán si los efectos directos e interacciones o efectos conjuntos entre los distintos factores del modelo final tienen una influencia positiva o negativa sobre el valor de las diferentes frecuencias conjuntas de la tabla de contingencia, lo que informará no solo de si existe asociación entre factores o no; sino también de, en caso de existir, de cómo se materializa tal asociación.</p>
<p>Para ejemplificar la especificación, estimación e interpretación de los modelos log-lineales aplicados a tablas de contingencia, vamos a plantear un caso en el que entran en juego 3 factores o atributos, que caracterizan a un conjunto o muestra de 474 empresas eólicas. Estos factores o atributos son:</p>
<ul>
<li><p><strong>DIMENSION:</strong> tamaño del grupo empresarial al que pertenece la empresa en cuestión. Tiene tres niveles: grande, media y reducida.</p></li>
<li><p><strong>AUTOFINA:</strong> capacidad de autofinanciación de la empresa a medio y largo plazo. Tiene tres niveles: alta, positiva y negativa.</p></li>
<li><p><strong>FJUR</strong>: forma jurídica. Tiene dos posibles categorías: Sociedad anónima o Sociedad limitada.</p></li>
</ul>
<p>Los datos se encuentran alojados en la hoja “Datos” del archivo de Microsoft® Excel® “<a href="https://docs.google.com/spreadsheets/d/1f0OQaxyzjKIIXrqhCFL1vIBNcLLGx6R4/edit?usp=sharing&amp;ouid=115375878280465826079&amp;rtpof=true&amp;sd=true">eolica_contingencia2.xlsx</a>”. El código a desarrollar está disponible en el <em>script</em> “<a href="https://drive.google.com/file/d/1xMmM2nrSHBCMU1EEDePb2BRuv_TbD-7r/view?usp=sharing">loglineal_eolica.R</a>”. Puede desarrollarse el ejemplo creando para ello un proyecto de RStudio, por ejemplo, el proyecto “loglineal”.</p>
<p>Comenzando a ejecutar el código presente en el <em>script</em>, la primera parte se dedica, como es habitual, a la gestión de los datos: borrado previo de memoria, importación de los datos alojados en el archivo de Excel y volcado a un <em>data frame</em>, corrección del nombre de las filas de este, y selección de las variables categóricas del estudio:</p>
<div class="sourceCode" id="cb373"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Analisis de Asociacion y modelos log-lineales de eolicas</span></span>
<span><span class="co"># Disculpen por la falta de tildes!</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># DATOS</span></span>
<span></span>
<span>  <span class="co"># Importando datos</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://readxl.tidyverse.org">readxl</a></span><span class="op">)</span></span>
<span>    <span class="va">eolicas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_excel</a></span><span class="op">(</span><span class="st">"eolica_contingencia2.xlsx"</span>, sheet <span class="op">=</span><span class="st">"Datos"</span><span class="op">)</span></span>
<span>    <span class="va">eolicas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">eolicas</span>, row.names <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span> <span class="op">(</span><span class="va">eolicas</span><span class="op">)</span></span>
<span></span>
<span>  <span class="co"># Seleccionando factores/atributos para el analisis</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span>    <span class="va">originales2</span> <span class="op">&lt;-</span> <span class="va">eolicas</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">DIMENSION</span>, <span class="va">AUTOFINA</span>, <span class="va">FJUR</span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span> <span class="op">(</span><span class="va">originales2</span><span class="op">)</span></span></code></pre></div>
<div class="sourceCode" id="cb374"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># Analisis de Asociacion y modelos log-lineales de eolicas</span></span>
<span><span class="co"># Disculpen por la falta de tildes!</span></span>
<span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/rm.html">rm</a></span><span class="op">(</span>list <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/ls.html">ls</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># DATOS</span></span>
<span></span>
<span>  <span class="co"># Importando datos</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://readxl.tidyverse.org">readxl</a></span><span class="op">)</span></span>
<span>    <span class="va">eolicas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://readxl.tidyverse.org/reference/read_excel.html">read_excel</a></span><span class="op">(</span><span class="st">"eolica_contingencia2.xlsx"</span>, sheet <span class="op">=</span><span class="st">"Datos"</span><span class="op">)</span></span>
<span>    <span class="va">eolicas</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span><span class="va">eolicas</span>, row.names <span class="op">=</span> <span class="fl">1</span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span> <span class="op">(</span><span class="va">eolicas</span><span class="op">)</span></span>
<span></span>
<span>  <span class="co"># Seleccionando factores/atributos para el analisis</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span></span>
<span>    <span class="va">originales2</span> <span class="op">&lt;-</span> <span class="va">eolicas</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">DIMENSION</span>, <span class="va">AUTOFINA</span>, <span class="va">FJUR</span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span> <span class="op">(</span><span class="va">originales2</span><span class="op">)</span></span></code></pre></div>
<pre><code>##      MARGEN            SOLVENCIA            COM           
##  Min.   : -4124.22   Min.   :-1162.21   Length:474        
##  1st Qu.:    14.09   1st Qu.:   13.95   Class :character  
##  Median :    42.64   Median :   39.36   Mode  :character  
##  Mean   :   794.48   Mean   :   38.19                     
##  3rd Qu.:    64.82   3rd Qu.:   72.69                     
##  Max.   :298700.00   Max.   :  100.00                     
##  NA's   :87                                               
## 
##      FJUR                ING                NCOMP      
##  Length:474         Min.   :     0.11   Min.   :    0  
##  Class :character   1st Qu.:   392.92   1st Qu.:    3  
##  Mode  :character   Median :  3221.00   Median :   78  
##                     Mean   :  8128.59   Mean   : 1193  
##                     3rd Qu.:  7709.18   3rd Qu.:  392  
##                     Max.   :364989.00   Max.   :72434  
##                     NA's   :87          NA's   :1      
## 
##       RES                ACTIVO              FPIOS           
##  Min.   :-16107.21   Min.   :9.600e-01   Min.   : -51817.36  
##  1st Qu.:     3.09   1st Qu.:4.702e+02   1st Qu.:     67.13  
##  Median :   382.71   Median :8.103e+03   Median :   1578.00  
##  Mean   :  2164.98   Mean   :3.899e+04   Mean   :  15932.61  
##  3rd Qu.:  2413.00   3rd Qu.:3.115e+04   3rd Qu.:   8503.93  
##  Max.   : 78290.00   Max.   :2.429e+06   Max.   :1382020.00  
##  NA's   :52                                                  
## 
##      RENECO              RENFIN            LIQUIDEZ       
##  Min.   : -269.046   Min.   : -687.42   Min.   :   0.000  
##  1st Qu.:    0.000   1st Qu.:    0.00   1st Qu.:   0.621  
##  Median :    6.005   Median :   16.29   Median :   1.768  
##  Mean   :  151.080   Mean   :  194.65   Mean   :  23.474  
##  3rd Qu.:   17.506   3rd Qu.:   46.66   3rd Qu.:   3.947  
##  Max.   :66538.096   Max.   :67943.49   Max.   :1622.359  
##                                         NA's   :14        
## 
##     APALANCA          DIMENSION           AUTOFINA        
##  Min.   : -7016.77   Length:474         Length:474        
##  1st Qu.:     0.00   Class :character   Class :character  
##  Median :    22.64   Mode  :character   Mode  :character  
##  Mean   :   769.68                                        
##  3rd Qu.:   201.63                                        
##  Max.   :177381.90                                        
## 
##    Length     Class      Mode 
##       474 character character</code></pre>
<p>El <em>data frame</em> “originales2” albergará los tres factores o atributos del análisis:</p>
<pre><code>##   DIMENSION           AUTOFINA             FJUR          
##  Length:474         Length:474         Length:474        
##  Class :character   Class :character   Class :character  
##  Mode  :character   Mode  :character   Mode  :character</code></pre>
<p>Posteriormente se desarrolla la localización y tratamiento de <em>missing data</em>, ya que para realizar el análisis es necesario que todos los casos posean dato en todas las variables. Para tener una idea general, se puede recurrir a la función <code><a href="https://docs.ropensci.org/visdat/reference/vis_miss.html">vis_miss()</a></code> del paquete <a href="https://docs.ropensci.org/visdat/">visdat</a>, que localizará gráficamente los <em>missing values</em> de las diferentes variables, y calculará el porcentaje de casos que supone, con respecto al total de observaciones. En el ejemplo, los casos con missing data se concentran en el atributo o factor AUTOFINA, con 133 casos. El nombre concreto de los casos afectados se visualiza con un filtro construido a partir de la función <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> del paquete <a href="https://dplyr.tidyverse.org">dplyr</a>:</p>
<div class="sourceCode" id="cb377"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="co"># Identificando missing values.</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://docs.ropensci.org/visdat/">visdat</a></span><span class="op">)</span></span>
<span>    <span class="fu"><a href="https://docs.ropensci.org/visdat/reference/vis_miss.html">vis_miss</a></span><span class="op">(</span><span class="va">originales2</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-315-1.png" width="672"></div>
<div class="sourceCode" id="cb378"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">originales2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">DIMENSION</span><span class="op">)</span> <span class="op">|</span></span>
<span>                           <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">AUTOFINA</span><span class="op">)</span><span class="op">|</span></span>
<span>                           <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">FJUR</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">DIMENSION</span>, <span class="va">AUTOFINA</span>, <span class="va">FJUR</span><span class="op">)</span>  </span></code></pre></div>
<pre><code>##                                                               DIMENSION AUTOFINA              FJUR
## Sierra de Selva SL                                               GRANDE     &lt;NA&gt; Sociedad limitada
## Eolica de Rubio SL                                               GRANDE     &lt;NA&gt; Sociedad limitada
## Fuerzas Energeticas DEL SUR de Europa II SL.                     GRANDE     &lt;NA&gt; Sociedad limitada
## Parque Eolico de LA Bobia Y SAN Isidro Sociedad Limitada       REDUCIDA     &lt;NA&gt; Sociedad limitada
## Engasa Eolica SA                                                  MEDIA     &lt;NA&gt;  Sociedad anonima
## Parque Eolico de Ameixenda-Filgueira SL                        REDUCIDA     &lt;NA&gt; Sociedad limitada
## Compañia Eolica Granadina SA                                   REDUCIDA     &lt;NA&gt;  Sociedad anonima
## Suresa Retama S.L.                                               GRANDE     &lt;NA&gt; Sociedad limitada
## Parque Eolico de Adraño SL                                     REDUCIDA     &lt;NA&gt; Sociedad limitada
## M Torres Desarrollos Energeticos SL                            REDUCIDA     &lt;NA&gt; Sociedad limitada
## Corporacion Eolica de Valdivia SL                                GRANDE     &lt;NA&gt; Sociedad limitada
## Parque Eolico de A Ruña SL                                     REDUCIDA     &lt;NA&gt; Sociedad limitada
## Molinos DEL Moncayo SL.                                        REDUCIDA     &lt;NA&gt; Sociedad limitada
## Eolico Alijar SA                                                 GRANDE     &lt;NA&gt;  Sociedad anonima
## Parque Eolico de Vicedo SL                                     REDUCIDA     &lt;NA&gt; Sociedad limitada
## Eolica de Villanueva SL                                          GRANDE     &lt;NA&gt; Sociedad limitada
## Parque Eolico de Virxe DO Monte SL                             REDUCIDA     &lt;NA&gt; Sociedad limitada
## Estructuras Y Revestimiento de Galicia SL                      REDUCIDA     &lt;NA&gt; Sociedad limitada
## Energias Renovables EL Abra SL                                   GRANDE     &lt;NA&gt; Sociedad limitada
## Proyectos Eolicos Aragoneses SL                                REDUCIDA     &lt;NA&gt; Sociedad limitada
## Soslaires Canarias SL                                          REDUCIDA     &lt;NA&gt; Sociedad limitada
## Eolica Cantabria SA                                            REDUCIDA     &lt;NA&gt;  Sociedad anonima
## Señorio de Bariain SA                                          REDUCIDA     &lt;NA&gt;  Sociedad anonima
## Energetica DEL Montalt SL                                      REDUCIDA     &lt;NA&gt; Sociedad limitada
## Eolica Lodosa SL                                               REDUCIDA     &lt;NA&gt; Sociedad limitada
## Parque Eolico LA Union S.L.                                    REDUCIDA     &lt;NA&gt; Sociedad limitada
## Eolica Pueyo SL                                                REDUCIDA     &lt;NA&gt; Sociedad limitada
## Parsona Corporacion SL.                                        REDUCIDA     &lt;NA&gt; Sociedad limitada
## Infraestructuras Electricas LA Mudarra SL.                       GRANDE     &lt;NA&gt; Sociedad limitada
## Eolica Unzue SL                                                REDUCIDA     &lt;NA&gt; Sociedad limitada
## Technical Services Wind SL.                                    REDUCIDA     &lt;NA&gt; Sociedad limitada
## Saltos DEL Mundo SL                                            REDUCIDA     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos LA Plana SA                                 GRANDE     &lt;NA&gt;  Sociedad anonima
## Renovalia Reserve SL.                                             MEDIA     &lt;NA&gt; Sociedad limitada
## Eolpop SL.                                                     REDUCIDA     &lt;NA&gt; Sociedad limitada
## Emprendimientos Y Desarrollo de Iniciativas Energeticas SL     REDUCIDA     &lt;NA&gt; Sociedad limitada
## Megaturbinas Arinaga SA                                        REDUCIDA     &lt;NA&gt;  Sociedad anonima
## Sunterra XXI Sociedad Limitada.                                REDUCIDA     &lt;NA&gt; Sociedad limitada
## Aizdegi SL                                                     REDUCIDA     &lt;NA&gt; Sociedad limitada
## Parque Eolico LA Sargilla Sociedad Anonima.                    REDUCIDA     &lt;NA&gt;  Sociedad anonima
## Intercon SA                                                    REDUCIDA     &lt;NA&gt;  Sociedad anonima
## Altosalvo SL                                                   REDUCIDA     &lt;NA&gt; Sociedad limitada
## Bluefloat Energy International SL.                             REDUCIDA     &lt;NA&gt; Sociedad limitada
## Corolla Power 1 SL                                             REDUCIDA     &lt;NA&gt; Sociedad limitada
## Corolla Power 3 SL                                             REDUCIDA     &lt;NA&gt; Sociedad limitada
## Parque Energetico de G C SL                                    REDUCIDA     &lt;NA&gt; Sociedad limitada
## Dapasa Servicios E Inversiones SL                              REDUCIDA     &lt;NA&gt; Sociedad limitada
## EL Guijorral SL                                                REDUCIDA     &lt;NA&gt; Sociedad limitada
## Minicentrales Bouza Vella SL                                   REDUCIDA     &lt;NA&gt; Sociedad limitada
## Locus Mentis SL                                                REDUCIDA     &lt;NA&gt; Sociedad limitada
## Vento Laracha SL.                                                 MEDIA     &lt;NA&gt; Sociedad limitada
## Huerto Solar EL Tronco SL                                      REDUCIDA     &lt;NA&gt; Sociedad limitada
## Fotovoltaica LA Solana SL                                      REDUCIDA     &lt;NA&gt; Sociedad limitada
## Fargo MAS 3 SL                                                 REDUCIDA     &lt;NA&gt; Sociedad limitada
## Naduele SL                                                     REDUCIDA     &lt;NA&gt; Sociedad limitada
## Maririas Energy SL                                             REDUCIDA     &lt;NA&gt; Sociedad limitada
## Helios Almaden Sociedad Limitada.                              REDUCIDA     &lt;NA&gt; Sociedad limitada
## Explotaciones MI Cobijo SL.                                    REDUCIDA     &lt;NA&gt; Sociedad limitada
## Catral Renovables SL                                           REDUCIDA     &lt;NA&gt; Sociedad limitada
## Energia Solar Turolense SL                                     REDUCIDA     &lt;NA&gt; Sociedad limitada
## AV Serra de Liñares SL.                                           MEDIA     &lt;NA&gt; Sociedad limitada
## Parque Eolico Donado SL                                          GRANDE     &lt;NA&gt; Sociedad limitada
## AV Paxareiras SL.                                                 MEDIA     &lt;NA&gt; Sociedad limitada
## Terranova Energy Corporation SA                                  GRANDE     &lt;NA&gt;  Sociedad anonima
## AV Serra DO Farelo SL.                                            MEDIA     &lt;NA&gt; Sociedad limitada
## Eolica de Cordales BIS SL.                                        MEDIA     &lt;NA&gt; Sociedad limitada
## AV Cernego SL.                                                    MEDIA     &lt;NA&gt; Sociedad limitada
## AV Outeiro Rubio SL.                                              MEDIA     &lt;NA&gt; Sociedad limitada
## Airosa Vento SL                                                   MEDIA     &lt;NA&gt; Sociedad limitada
## Eolica de Cordales SL.                                            MEDIA     &lt;NA&gt; Sociedad limitada
## Enerfin Renovables IV SL.                                        GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Jupiter Sociedad Limitada.                  GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Oberon Sociedad Limitada.                   GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Pluton Sociedad Limitada.                   GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Saturno Sociedad Limitada.                  GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Titan Sociedad Limitada.                    GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Urano Sociedad Limitada.                    GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Venus Sociedad Limitada.                    GRANDE     &lt;NA&gt; Sociedad limitada
## Puerto Rosario Solar 3 Sociedad Limitada.                        GRANDE     &lt;NA&gt; Sociedad limitada
## IM2 Energia Solar Proyecto 24 SL.                                 MEDIA     &lt;NA&gt; Sociedad limitada
## Parque Eolico Punta Langosteira SL.                            REDUCIDA     &lt;NA&gt; Sociedad limitada
## Desarrollos Fotovoltaicos Fuentes SL.                            GRANDE     &lt;NA&gt; Sociedad limitada
## Guadalaviar Consorcio Eolico SA.                                 GRANDE     &lt;NA&gt;  Sociedad anonima
## Desarrollo Eolico LAS Majas Xxxi SL.                             GRANDE     &lt;NA&gt; Sociedad limitada
## Puerto Rosario Solar 2 Sociedad Limitada.                        GRANDE     &lt;NA&gt; Sociedad limitada
## Energias Renovables de Hidra SL.                                 GRANDE     &lt;NA&gt; Sociedad limitada
## Energias Renovables de Cilene SL.                                GRANDE     &lt;NA&gt; Sociedad limitada
## Desarrollo Eolico LAS Majas XV SL.                               GRANDE     &lt;NA&gt; Sociedad limitada
## Renovacyl SA                                                     GRANDE     &lt;NA&gt;  Sociedad anonima
## Sistemas Energeticos DEL SUR SA                                  GRANDE     &lt;NA&gt;  Sociedad anonima
## Eolica Santa Teresa Sociedad Limitada.                         REDUCIDA     &lt;NA&gt; Sociedad limitada
## Lan2030 Toroña S.L.                                               MEDIA     &lt;NA&gt; Sociedad limitada
## Gerr Grupo Energetico XXI SA                                     GRANDE     &lt;NA&gt;  Sociedad anonima
## Belidia Energy SL.                                                MEDIA     &lt;NA&gt; Sociedad limitada
## Parc Tramuntana SL.                                            REDUCIDA     &lt;NA&gt; Sociedad limitada
## Aerogeneracion Galicia SL                                      REDUCIDA     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power A Marabilla, S.L.                           GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Alto DO Rodicio II, S.L.                    GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power AS Lagoas, S.L.                             GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Campos Vellos, S.L.                         GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Cardon, S.L.                                GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Cedeira, S.L.                               GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Cervo, S.L.                                 GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Cordobelas, S.L.                            GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Coto DOS Chaos, S.L.                        GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Dunas, S.L.                                 GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Esteiro, S.L.                               GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Guanche, S.L.                               GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Huracan, S.L.                               GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Lamas II, S.L.                              GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Mojo, S.L.                                  GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Montoxo, S.L.                               GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power O Barral, S.L.                              GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Piñeiro, S.L.                               GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Punta Candieira, S.L.                       GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Regoa, S.L.                                 GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power SAN Isidro, S.L.                            GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power SAN Roman, S.L.                             GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Suime, S.L.                                 GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Teixido, S.L.                               GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Tormenta, S.L.                              GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Vaqueira, S.L.                              GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Vilas, S.L.                                 GRANDE     &lt;NA&gt; Sociedad limitada
## Greenalia Wind Power Xesteiron, S.L.                             GRANDE     &lt;NA&gt; Sociedad limitada
## Infraestructuras Para EL Desarrollo de Energias Renovables SL     MEDIA     &lt;NA&gt; Sociedad limitada
## Renovables DEL Cantabrico Sociedad Limitada.                   REDUCIDA     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Erbania 1, Sociedad Limitada.               GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Erbania 2, Sociedad Limitada.               GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Marte Sociedad Limitada.                    GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Mercurio Sociedad Limitada.                 GRANDE     &lt;NA&gt; Sociedad limitada
## Sistemas Energeticos Neptuno Sociedad Limitada.                  GRANDE     &lt;NA&gt; Sociedad limitada
## Wind Premier Monte Redondo, S.L.                                 GRANDE     &lt;NA&gt; Sociedad limitada
## Wind Premier Serra Pequena, S.L.                                 GRANDE     &lt;NA&gt; Sociedad limitada</code></pre>
<p>Se decide eliminar los casos que carecen de valor en el atributo AUTOFINA, lo que se realiza mediante otro filtro:</p>
<div class="sourceCode" id="cb380"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">originales2</span> <span class="op">&lt;-</span> <span class="va">originales2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">DIMENSION</span><span class="op">)</span> <span class="op">&amp;</span></span>
<span>           <span class="op">!</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">AUTOFINA</span><span class="op">)</span> <span class="op">&amp;</span></span>
<span>           <span class="op">!</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">FJUR</span><span class="op">)</span><span class="op">)</span> </span></code></pre></div>
<p>El siguiente bloque se ocupa de crear el objeto “table” que recoge la tabla de contingencia formada al cruzar la distribución de las frecuencias o casos entre las diferentes categorías de los distintos factores. La función para convertir el <em>data frame</em> en una estructura de almacenamiento de datos especial llamada table (que es la <strong>tabla de contingencia</strong>) es precisamente <code><a href="https://rdrr.io/r/base/table.html">table()</a></code>. La tabla de contingencia construida, de nombre “tab.originales2”, es posteriormente presentada como una tabla diseñada a partir de la función <code><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable()</a></code> del paquete <a href="https://yihui.org/knitr/">knitr</a>, y otras funciones incluidas en el paquete <a href="http://haozhu233.github.io/kableExtra/">kableExtra</a>:</p>
<div class="sourceCode" id="cb381"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># TABLA DE CONTINGENCIA</span></span>
<span></span>
<span>  <span class="va">tab.originales2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/table.html">table</a></span><span class="op">(</span><span class="va">originales2</span><span class="op">)</span></span>
<span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://yihui.org/knitr/">knitr</a></span><span class="op">)</span></span>
<span>  <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="http://haozhu233.github.io/kableExtra/">kableExtra</a></span><span class="op">)</span></span>
<span>  <span class="va">knitr.table.format</span> <span class="op">=</span> <span class="st">"html"</span></span>
<span></span>
<span>  <span class="va">tab.originales2</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>format <span class="op">=</span> <span class="va">knitr.table.format</span>,</span>
<span>         caption<span class="op">=</span><span class="st">"Empresas eólicas"</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>full_width <span class="op">=</span> <span class="cn">F</span>,</span>
<span>                  bootstrap_options <span class="op">=</span> <span class="st">"striped"</span>, <span class="st">"bordered"</span>, <span class="st">"condensed"</span>,</span>
<span>                  position <span class="op">=</span> <span class="st">"center"</span>,</span>
<span>                  font_size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/row_spec.html">row_spec</a></span><span class="op">(</span><span class="fl">0</span>, bold<span class="op">=</span> <span class="cn">T</span>, align <span class="op">=</span> <span class="st">"c"</span><span class="op">)</span></span></code></pre></div>
<div class="inline-table"><table class="table table-striped" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-318">Table 10.5: </span><span id="tab:unnamed-chunk-318">Table 10.6: </span>Empresas eólicas
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
DIMENSION
</th>
<th style="text-align:left;font-weight: bold;text-align: center;">
AUTOFINA
</th>
<th style="text-align:left;font-weight: bold;text-align: center;">
FJUR
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Freq
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
GRANDE
</td>
<td style="text-align:left;">
ALTA
</td>
<td style="text-align:left;">
Sociedad anonima
</td>
<td style="text-align:right;">
34
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA
</td>
<td style="text-align:left;">
ALTA
</td>
<td style="text-align:left;">
Sociedad anonima
</td>
<td style="text-align:right;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA
</td>
<td style="text-align:left;">
ALTA
</td>
<td style="text-align:left;">
Sociedad anonima
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE
</td>
<td style="text-align:left;">
NEGATIVA
</td>
<td style="text-align:left;">
Sociedad anonima
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA
</td>
<td style="text-align:left;">
NEGATIVA
</td>
<td style="text-align:left;">
Sociedad anonima
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA
</td>
<td style="text-align:left;">
NEGATIVA
</td>
<td style="text-align:left;">
Sociedad anonima
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE
</td>
<td style="text-align:left;">
POSITIVA
</td>
<td style="text-align:left;">
Sociedad anonima
</td>
<td style="text-align:right;">
11
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA
</td>
<td style="text-align:left;">
POSITIVA
</td>
<td style="text-align:left;">
Sociedad anonima
</td>
<td style="text-align:right;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA
</td>
<td style="text-align:left;">
POSITIVA
</td>
<td style="text-align:left;">
Sociedad anonima
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE
</td>
<td style="text-align:left;">
ALTA
</td>
<td style="text-align:left;">
Sociedad limitada
</td>
<td style="text-align:right;">
45
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA
</td>
<td style="text-align:left;">
ALTA
</td>
<td style="text-align:left;">
Sociedad limitada
</td>
<td style="text-align:right;">
22
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA
</td>
<td style="text-align:left;">
ALTA
</td>
<td style="text-align:left;">
Sociedad limitada
</td>
<td style="text-align:right;">
49
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE
</td>
<td style="text-align:left;">
NEGATIVA
</td>
<td style="text-align:left;">
Sociedad limitada
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA
</td>
<td style="text-align:left;">
NEGATIVA
</td>
<td style="text-align:left;">
Sociedad limitada
</td>
<td style="text-align:right;">
16
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA
</td>
<td style="text-align:left;">
NEGATIVA
</td>
<td style="text-align:left;">
Sociedad limitada
</td>
<td style="text-align:right;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE
</td>
<td style="text-align:left;">
POSITIVA
</td>
<td style="text-align:left;">
Sociedad limitada
</td>
<td style="text-align:right;">
54
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA
</td>
<td style="text-align:left;">
POSITIVA
</td>
<td style="text-align:left;">
Sociedad limitada
</td>
<td style="text-align:right;">
33
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA
</td>
<td style="text-align:left;">
POSITIVA
</td>
<td style="text-align:left;">
Sociedad limitada
</td>
<td style="text-align:right;">
41
</td>
</tr>
</tbody>
</table></div>
<p>Un modo visual de obtener una primera idea de las relaciones que se incluyen en la tabla es construir un gráfico de mosaico, con la función <code><a href="https://rdrr.io/pkg/vcd/man/mosaic.html">mosaic()</a></code> del paquete <code>{vcd}</code>, en la que el área de los diferentes rectángulos sea proporcional a la frecuencia conjunta correspondiente:</p>
<div class="sourceCode" id="cb382"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="co"># Representación gráfica de la tabla con mosaico</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va">vcd</span><span class="op">)</span></span>
<span>   <span class="fu"><a href="https://rdrr.io/pkg/vcd/man/mosaic.html">mosaic</a></span><span class="op">(</span><span class="va">tab.originales2</span>,</span>
<span>          main <span class="op">=</span> <span class="st">"Eólicas: Dimensión Matriz y Valoración Expertos."</span>,</span>
<span>          shade <span class="op">=</span> <span class="cn">T</span>,</span>
<span>          gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/vcd/man/shadings.html">shading_Marimekko</a></span><span class="op">(</span><span class="va">tab.originales2</span><span class="op">)</span>,</span>
<span>          main_gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fontsize <span class="op">=</span> <span class="fl">14</span><span class="op">)</span>,</span>
<span>          sub_gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fontsize <span class="op">=</span> <span class="fl">12</span><span class="op">)</span>,</span>
<span>          labeling_args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>gp_labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fontsize <span class="op">=</span> <span class="fl">7</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-319-1.png" width="672"></div>
<p>En cuanto a las frecuencias marginales de cada nivel o categoría de los tres atributos o factores, pueden representarse estas mediante gráficos de barras, generados mediante las funciones del paquete <a href="https://ggplot2.tidyverse.org">ggplot2</a>, y reunidos en una sola imagen mediante el paquete <a href="https://patchwork.data-imaginist.com">patchwork</a>. El código es el siguiente:</p>
<div class="sourceCode" id="cb383"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="co"># Representando frecuencias de categorias en factores</span></span>
<span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span> <span class="op">(</span><span class="va"><a href="https://patchwork.data-imaginist.com">patchwork</a></span><span class="op">)</span></span>
<span></span>
<span>    <span class="va">g1b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">originales2</span>, map<span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span> <span class="va">DIMENSION</span>,</span>
<span>                                        fill <span class="op">=</span> <span class="va">DIMENSION</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Dimensión del grupo empresarial"</span>,</span>
<span>            subtitle <span class="op">=</span> <span class="st">"Empresas eólicas"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Frecuencias"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Dimensión"</span><span class="op">)</span> </span>
<span></span>
<span>    <span class="va">g2b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">originales2</span>, map<span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span> <span class="va">AUTOFINA</span>,</span>
<span>                                        fill <span class="op">=</span> <span class="va">AUTOFINA</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Valoración de expertos"</span>,</span>
<span>            subtitle <span class="op">=</span> <span class="st">"Empresas eólicas"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Frecuencias"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Valoración"</span><span class="op">)</span> </span>
<span></span>
<span>    <span class="va">g3b</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="va">originales2</span>, map<span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span>x<span class="op">=</span> <span class="va">FJUR</span>,</span>
<span>                                        fill <span class="op">=</span> <span class="va">FJUR</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_bar.html">geom_bar</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span><span class="op">(</span><span class="st">"Forma Jurídica"</span>,</span>
<span>            subtitle <span class="op">=</span> <span class="st">"Empresas eólicas"</span><span class="op">)</span> <span class="op">+</span> </span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span><span class="op">(</span><span class="st">"Frecuencias"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span><span class="op">(</span><span class="st">"Forma Jurídica"</span><span class="op">)</span> </span>
<span></span>
<span>    <span class="op">(</span><span class="va">g1b</span> <span class="op">/</span> <span class="va">g2b</span> <span class="op">/</span> <span class="va">g3b</span><span class="op">)</span> <span class="op">+</span> <span class="fu"><a href="https://patchwork.data-imaginist.com/reference/plot_annotation.html">plot_annotation</a></span><span class="op">(</span>title <span class="op">=</span> <span class="st">"Frecuencias Marginales."</span>,</span>
<span>                      theme <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/theme.html">theme</a></span><span class="op">(</span>plot.title <span class="op">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/element.html">element_text</a></span><span class="op">(</span>size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-320-1.png" width="672"></div>
<p>Los modelos log-lineales se especifican y estiman mediante la función <code>loglm()</code> de la librería <a href="http://www.stats.ox.ac.uk/pub/MASS4/">MASS</a> (el paquete MASS lo hemos activado junto a la propia función loglm() ya que, de hacerlo con la función <code><a href="https://rdrr.io/r/base/library.html">library()</a></code>, se crea un conflicto con la función <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> del paquete <a href="https://dplyr.tidyverse.org">dplyr</a>).</p>
<p>Cuando se estiman los modelos, los diferentes resultados se almacenan en una lista. Entre estos elementos se encuentran los parámetros estimados, que, dentro de la lista de resultados, se almacenan, a su vez, en una estructura que, según la especificación que se elija del modelo, puede llegar a ser compleja. para facilitar el trabajo de extracción de los parámetros y almacenamiento en un data frame, se ha desarrollado una función denominada <code>extraer_coeficientes()</code>. Debido a la complejidad del código, y antes de proceder a estimar los modelos, exponemos el código de la función, que recibe como input o argumento el nombre de un modelo log-lineal estimado, y devuelve como output un data frame con los coeficientes o parámetros estimados:</p>
<div class="sourceCode" id="cb384"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co"># MODELOS LOG-LINEALES</span></span>
<span></span>
<span><span class="co"># Función para extraer coeficientes y sus nombres de un modelo ##########</span></span>
<span><span class="va">extraer_coeficientes</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="co"># Extraer los parámetros del modelo</span></span>
<span>  <span class="va">parametros</span> <span class="op">&lt;-</span> <span class="va">modelo</span><span class="op">$</span><span class="va">param</span></span>
<span>  </span>
<span>  <span class="co"># Crear listas para almacenar nombres y valores de coeficientes</span></span>
<span>  <span class="va">coef_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">)</span></span>
<span>  <span class="va">coef_values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Función para generar nombres de coeficientes</span></span>
<span>  <span class="va">generate_coef_name</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">levels</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">levels</span>, collapse <span class="op">=</span> <span class="st">":"</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span>  </span>
<span>  <span class="co"># Recorrer los coeficientes y extraer los nombres y valores</span></span>
<span>  <span class="kw">for</span> <span class="op">(</span><span class="va">term</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">parametros</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="kw">if</span> <span class="op">(</span><span class="va">term</span> <span class="op">==</span> <span class="st">"(Intercept)"</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="va">coef_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">coef_names</span>, <span class="st">"T. Independiente"</span><span class="op">)</span></span>
<span>      <span class="va">coef_values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">coef_values</span>, <span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span>    <span class="op">}</span> <span class="kw">else</span> <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/matrix.html">is.matrix</a></span><span class="op">(</span><span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="co"># Si es una matriz, recorrer filas y columnas</span></span>
<span>      <span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="kw">for</span> <span class="op">(</span><span class="va">j</span> <span class="kw">in</span> <span class="fl">1</span><span class="op">:</span><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">ncol</a></span><span class="op">(</span><span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>          <span class="va">coef_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">coef_names</span>,</span>
<span>                          <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/colnames.html">rownames</a></span><span class="op">(</span><span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">)</span><span class="op">[</span><span class="va">i</span><span class="op">]</span>,</span>
<span>                                <span class="fu"><a href="https://rdrr.io/r/base/colnames.html">colnames</a></span><span class="op">(</span><span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">)</span><span class="op">[</span><span class="va">j</span><span class="op">]</span>,</span>
<span>                                sep <span class="op">=</span> <span class="st">":"</span><span class="op">)</span><span class="op">)</span></span>
<span>          <span class="va">coef_values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">coef_values</span>, <span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="va">i</span>, <span class="va">j</span><span class="op">]</span><span class="op">)</span></span>
<span>        <span class="op">}</span></span>
<span>      <span class="op">}</span></span>
<span>    <span class="op">}</span> <span class="kw">else</span> <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/array.html">is.array</a></span><span class="op">(</span><span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>      <span class="co"># Si es un array de más de dos dimensiones</span></span>
<span>      <span class="va">dims</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/dim.html">dim</a></span><span class="op">(</span><span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span>      <span class="va">dimnames_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/dimnames.html">dimnames</a></span><span class="op">(</span><span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span>      <span class="kw">for</span> <span class="op">(</span><span class="va">i</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">dims</span><span class="op">[</span><span class="fl">1</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="kw">for</span> <span class="op">(</span><span class="va">j</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">dims</span><span class="op">[</span><span class="fl">2</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>          <span class="kw">for</span> <span class="op">(</span><span class="va">k</span> <span class="kw">in</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq_len</a></span><span class="op">(</span><span class="va">dims</span><span class="op">[</span><span class="fl">3</span><span class="op">]</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>            <span class="va">coef_name</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span><span class="op">(</span><span class="va">dimnames_list</span><span class="op">[[</span><span class="fl">1</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="va">i</span><span class="op">]</span>,</span>
<span>                               <span class="va">dimnames_list</span><span class="op">[[</span><span class="fl">2</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="va">j</span><span class="op">]</span>,</span>
<span>                               <span class="va">dimnames_list</span><span class="op">[[</span><span class="fl">3</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="va">k</span><span class="op">]</span>,</span>
<span>                               sep <span class="op">=</span> <span class="st">":"</span><span class="op">)</span></span>
<span>            <span class="va">coef_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">coef_names</span>, <span class="va">coef_name</span><span class="op">)</span></span>
<span>            <span class="va">coef_values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">coef_values</span>,</span>
<span>                             <span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">[</span><span class="va">i</span>, <span class="va">j</span>, <span class="va">k</span><span class="op">]</span><span class="op">)</span></span>
<span>          <span class="op">}</span></span>
<span>        <span class="op">}</span></span>
<span>      <span class="op">}</span></span>
<span>    <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span></span>
<span>      <span class="va">levels</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span>      <span class="kw">for</span> <span class="op">(</span><span class="va">level</span> <span class="kw">in</span> <span class="va">levels</span><span class="op">)</span> <span class="op">{</span></span>
<span>        <span class="va">coef_names</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">coef_names</span>,</span>
<span>                        <span class="fu">generate_coef_name</span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">term</span>, <span class="va">level</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span>        <span class="va">coef_values</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">coef_values</span>,</span>
<span>                         <span class="va">parametros</span><span class="op">[[</span><span class="va">term</span><span class="op">]</span><span class="op">]</span><span class="op">[[</span><span class="va">level</span><span class="op">]</span><span class="op">]</span><span class="op">)</span></span>
<span>      <span class="op">}</span></span>
<span>    <span class="op">}</span></span>
<span>  <span class="op">}</span></span>
<span>  </span>
<span>  <span class="co"># Verificar la longitud de los vectores antes de crear el data frame</span></span>
<span>  <span class="kw">if</span> <span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">coef_names</span><span class="op">)</span> <span class="op">==</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="va">coef_values</span><span class="op">)</span><span class="op">)</span> <span class="op">{</span></span>
<span>    <span class="va">tabla_coeficientes</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>Coefficient <span class="op">=</span> <span class="va">coef_names</span>,</span>
<span>                                     Value <span class="op">=</span> <span class="va">coef_values</span>,</span>
<span>                                     stringsAsFactors <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/function.html">return</a></span><span class="op">(</span><span class="va">tabla_coeficientes</span><span class="op">)</span></span>
<span>  <span class="op">}</span> <span class="kw">else</span> <span class="op">{</span></span>
<span>    <span class="kw"><a href="https://rdrr.io/r/base/stop.html">stop</a></span><span class="op">(</span><span class="st">"Error: Las longitudes de coef_names y coef_values no coinciden."</span><span class="op">)</span></span>
<span>  <span class="op">}</span></span>
<span><span class="op">}</span></span>
<span><span class="co">############################################################################   </span></span></code></pre></div>
<p>Del mismo modo, se ha creado otra función para facilitar la pesentación de la información más importante que se genera con la estimación del modelo loglineal. Es la función <code>generar_solucion()</code>. Esta función recibe como argumento o <em>intput</em> el nombre del modelo estimado, y devuelve tres elementos: dos tablas diseñadas con <code><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable()</a></code>, que se almacenan en una lista, y un gráfico de <em>mosaico</em> que recoge los <strong>residuos del modelo</strong> (diferencias entre las frecuencias conjuntas reales u observadas de la tabla de contingencia, y sus estimaciones por parte del modelo). La primera de las tablas recoge las pruebas de validez de los modelos del <em>ratio de verosimilitud</em> (<code>deviance</code>), y de <em>Pearson</em>: nombre de la prueba, estadístico del contraste, grados de libertad y <em>p-valor</em>. La segunda tabla recoge los coeficientes o parámetros estimados, para lo cual la función llama, a su vez, a la función extraer_coeficientes(), toma el data frame que construya tal función, y la usa como base para diseñar la segunda tabla.</p>
<p>El código de la función es el siguiente:</p>
<div class="sourceCode" id="cb385"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="co">############################################################################</span></span>
<span><span class="co"># Función generar tablas y gráfico a partir de modelo log-lineal</span></span>
<span></span>
<span><span class="va">generar_solucion</span> <span class="op">&lt;-</span> <span class="kw">function</span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span> <span class="op">{</span></span>
<span>  <span class="co"># Extraer la información del modelo</span></span>
<span>  <span class="va">summary_modelo</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/summary.html">summary</a></span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Crear una tabla con la información relevante de las pruebas de validez</span></span>
<span>  <span class="va">tabla_informacion</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>    Statistic <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Likelihood Ratio"</span>, <span class="st">"Pearson"</span><span class="op">)</span>,</span>
<span>    X2 <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">summary_modelo</span><span class="op">$</span><span class="va">tests</span><span class="op">[</span><span class="fl">1</span>, <span class="st">"X^2"</span><span class="op">]</span>, <span class="va">summary_modelo</span><span class="op">$</span><span class="va">tests</span><span class="op">[</span><span class="fl">2</span>, <span class="st">"X^2"</span><span class="op">]</span><span class="op">)</span>,</span>
<span>    df <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">summary_modelo</span><span class="op">$</span><span class="va">tests</span><span class="op">[</span><span class="fl">1</span>, <span class="st">"df"</span><span class="op">]</span>, <span class="va">summary_modelo</span><span class="op">$</span><span class="va">tests</span><span class="op">[</span><span class="fl">2</span>, <span class="st">"df"</span><span class="op">]</span><span class="op">)</span>,</span>
<span>    P_value <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="va">summary_modelo</span><span class="op">$</span><span class="va">tests</span><span class="op">[</span><span class="fl">1</span>, <span class="st">"P(&gt; X^2)"</span><span class="op">]</span>, <span class="va">summary_modelo</span><span class="op">$</span><span class="va">tests</span><span class="op">[</span><span class="fl">2</span>, <span class="st">"P(&gt; X^2)"</span><span class="op">]</span><span class="op">)</span>,</span>
<span>    stringsAsFactors <span class="op">=</span> <span class="cn">FALSE</span></span>
<span>  <span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Formatear la tabla usando kable</span></span>
<span>  <span class="va">independencia_valida_tab</span> <span class="op">&lt;-</span> <span class="va">tabla_informacion</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>caption <span class="op">=</span><span class="st">"Validación del modelo"</span>,</span>
<span>          format <span class="op">=</span> <span class="st">"html"</span>,</span>
<span>          col.names <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Prueba"</span>, <span class="st">"Estadístico"</span>, <span class="st">"Grados Libertad"</span>, <span class="st">"P-valor"</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>full_width <span class="op">=</span> <span class="cn">F</span>,</span>
<span>                  bootstrap_options <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"striped"</span>, <span class="st">"bordered"</span>, <span class="st">"condensed"</span><span class="op">)</span>,</span>
<span>                  position <span class="op">=</span> <span class="st">"center"</span>,</span>
<span>                  font_size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/row_spec.html">row_spec</a></span><span class="op">(</span><span class="fl">0</span>, bold<span class="op">=</span> <span class="cn">T</span>, align <span class="op">=</span> <span class="st">"c"</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Extraer los coeficientes del modelo</span></span>
<span>  <span class="va">independencia_df</span> <span class="op">&lt;-</span> <span class="fu">extraer_coeficientes</span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Formatear la tabla de coeficientes usando kable</span></span>
<span>  <span class="va">independencia_coef_tab</span> <span class="op">&lt;-</span> <span class="va">independencia_df</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/knitr/man/kable.html">kable</a></span><span class="op">(</span>format <span class="op">=</span> <span class="st">"html"</span>,</span>
<span>          caption <span class="op">=</span><span class="st">"Coeficientes del modelo"</span>,</span>
<span>          digits <span class="op">=</span> <span class="fl">3</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/kable_styling.html">kable_styling</a></span><span class="op">(</span>full_width <span class="op">=</span> <span class="cn">F</span>,</span>
<span>                  bootstrap_options <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"striped"</span>, <span class="st">"bordered"</span>, <span class="st">"condensed"</span><span class="op">)</span>,</span>
<span>                  position <span class="op">=</span> <span class="st">"center"</span>,</span>
<span>                  font_size <span class="op">=</span> <span class="fl">12</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span></span>
<span>    <span class="fu"><a href="https://rdrr.io/pkg/kableExtra/man/row_spec.html">row_spec</a></span><span class="op">(</span><span class="fl">0</span>, bold<span class="op">=</span> <span class="cn">T</span>, align <span class="op">=</span> <span class="st">"c"</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Crear el gráfico de mosaico con los residuos y mostrarlo en pantalla directamente</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/graphics/plot.default.html">plot</a></span><span class="op">(</span><span class="va">modelo</span>, panel <span class="op">=</span> <span class="va">mosaic</span>,</span>
<span>       main<span class="op">=</span><span class="st">"Residuos del modelo"</span>,</span>
<span>       residuals_type <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"deviance"</span><span class="op">)</span>,</span>
<span>       gp <span class="op">=</span> <span class="va">shading_hcl</span>,</span>
<span>       gp_args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>interpolate <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">0</span>, <span class="fl">1</span><span class="op">)</span><span class="op">)</span>,</span>
<span>       main_gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fontsize <span class="op">=</span> <span class="fl">14</span><span class="op">)</span>,</span>
<span>       sub_gp <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fontsize <span class="op">=</span> <span class="fl">9</span><span class="op">)</span>,</span>
<span>       labeling_args <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>gp_labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/grid/gpar.html">gpar</a></span><span class="op">(</span>fontsize <span class="op">=</span> <span class="fl">7</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span>  </span>
<span>  <span class="co"># Guardar las tablas en una lista</span></span>
<span>  <span class="va">solucion_nombre</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"solucion_"</span>, <span class="fu"><a href="https://rdrr.io/r/base/deparse.html">deparse</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/substitute.html">substitute</a></span><span class="op">(</span><span class="va">modelo</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span>  <span class="va">solucion_lista</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span></span>
<span>    Informacion <span class="op">=</span> <span class="va">independencia_valida_tab</span>,</span>
<span>    Coeficientes <span class="op">=</span> <span class="va">independencia_coef_tab</span></span>
<span>  <span class="op">)</span></span>
<span>  </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/assign.html">assign</a></span><span class="op">(</span><span class="va">solucion_nombre</span>, <span class="va">solucion_lista</span>, envir <span class="op">=</span> <span class="va">.GlobalEnv</span><span class="op">)</span></span>
<span><span class="op">}</span></span>
<span><span class="co">##########################################################################</span></span></code></pre></div>
<p>Con el par de funciones anteriores, es fácil estimar un modelo log-lineal aplicado a tablas de contingencia y recopilar la información más relevante.</p>
<p>Comenzaremos por el <strong>modelo de independencia</strong>, que plantea que solo existen efectos directos en la determinación de las frecuencias conjuntas de la tabla (no-asociación entre factores). La especificación y estimación del modelo es la siguiente:</p>
<div class="sourceCode" id="cb386"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="co"># Modelo Independencia.</span></span>
<span></span>
<span>    <span class="va">modelo_indep</span> <span class="op">&lt;-</span> <span class="fu">MASS</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/MASS/man/loglm.html">loglm</a></span><span class="op">(</span><span class="op">~</span> <span class="va">DIMENSION</span> <span class="op">+</span> <span class="va">AUTOFINA</span> <span class="op">+</span> <span class="va">FJUR</span>,</span>
<span>                                data<span class="op">=</span> <span class="va">tab.originales2</span><span class="op">)</span></span>
<span></span>
<span>    <span class="fu">generar_solucion</span><span class="op">(</span><span class="va">modelo_indep</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-324-1.png" width="672"></div>
<p>Puede comprobarse que se ha creado la lista “solucion_modelo_indep”, que guarda dos elementos ($Informacion y $Coeficientes), y se ha generado el gráfico de mosaico de los residuos. Cuanto más intensos son los colores, mayores serán los residuos (en valor absoluto) y, por lo tanto, peor será el ajuste obtenido, lo que se deberá a que se ha considerado (erróneamente) que no hay interacción entre los factores (no asociación o independencia). En cuanto a los tonos de color:</p>
<ul>
<li><p><strong>Rectángulos azulados</strong>: Indican que la frecuencia observada es mayor que la frecuencia estimada por el modelo. Es decir, el modelo subestima la frecuencia observada.</p></li>
<li><p><strong>Rectángulos rojizos</strong>: Indican que la frecuencia observada es menor que la frecuencia estimada por el modelo. Es decir, el modelo sobreestima la frecuencia observada.</p></li>
</ul>
<p>En nuestro caso, existen frecuencias en los que los residuos toman colores bastante intensos, lo que hace pensar en que no se ha producido un buen ajuste. Como este modelo planteaba un escenario en el que no hay asociación entre los atributos; el gráfico parece apoyar la hipótesis de que sí existe asociación, al menos entre algunos de los factores o atributos.</p>
<p>Vamos a interpretar ahora el primer elemento de la lista “solucion_modelo_indep”, que es la tabla donde se disponen las pruebas de validez del modelo. Para obtener la tabla ejecutaremos:</p>
<div class="sourceCode" id="cb387"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">solucion_modelo_indep</span><span class="op">$</span><span class="va">Informacion</span></span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-bordered table-condensed" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-324">Table 10.7: </span>Validación del modelo
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
Prueba
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Estadístico
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Grados Libertad
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
P-valor
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Likelihood Ratio
</td>
<td style="text-align:right;">
59.48973
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
Pearson
</td>
<td style="text-align:right;">
66.55540
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table></div>
<p>En ambas pruebas (ratio de verosimilitud y Pearson) se obtiene un p-valor de 0. Teniendo en cuenta que la hipótesis nula de ambas pruebas es que existe un buen ajuste; la conclusión es que, según los resultados, <strong>el modelo de independencia no es capaz de representar la realidad con suficiente precisión</strong> (de ahí la magnitud de los residuos). Esto se puede interpretar, a su vez, como que <strong>se rechaza la hipótesis de independencia entre los factores</strong> y se admite que existe asociación entre, al menos, algunos de ellos.</p>
<p>Por último, vamos a mostrar el segundo elemento de la lista “solucion_modelo_indep”, que es la tabla donde se disponen los parámetros estimados del modelo, que en este caso corresponden solo a efectos directos o principales. Para obtener la tabla ejecutaremos:</p>
<div class="sourceCode" id="cb388"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">solucion_modelo_indep</span><span class="op">$</span><span class="va">Coeficientes</span></span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-bordered table-condensed" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-324">Table 10.7: </span>Coeficientes del modelo
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
Coefficient
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Value
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
T. Independiente
</td>
<td style="text-align:right;">
2.479
</td>
</tr>
<tr>
<td style="text-align:left;">
DIMENSION:GRANDE
</td>
<td style="text-align:right;">
0.297
</td>
</tr>
<tr>
<td style="text-align:left;">
DIMENSION:MEDIA
</td>
<td style="text-align:right;">
-0.253
</td>
</tr>
<tr>
<td style="text-align:left;">
DIMENSION:REDUCIDA
</td>
<td style="text-align:right;">
-0.044
</td>
</tr>
<tr>
<td style="text-align:left;">
AUTOFINA:ALTA
</td>
<td style="text-align:right;">
0.554
</td>
</tr>
<tr>
<td style="text-align:left;">
AUTOFINA:NEGATIVA
</td>
<td style="text-align:right;">
-1.049
</td>
</tr>
<tr>
<td style="text-align:left;">
AUTOFINA:POSITIVA
</td>
<td style="text-align:right;">
0.496
</td>
</tr>
<tr>
<td style="text-align:left;">
FJUR:Sociedad anonima
</td>
<td style="text-align:right;">
-0.686
</td>
</tr>
<tr>
<td style="text-align:left;">
FJUR:Sociedad limitada
</td>
<td style="text-align:right;">
0.686
</td>
</tr>
</tbody>
</table></div>
<p>ssage=FALSE, warning=FALSE}</p>
<p>Puede destacarse el hecho de que, que la capacidad de autofinanciación sea negativa, tiende a provocar una reducción del número de casos en las frecuencias conjuntas implicadas (signo negativo) También el hecho de que la forma jurídica adoptada sea la de <em>Sociedad Anónima</em>. En el extremo opuesto, destacan los signos positivos de la forma jurídica de <em>Sociedad Limitada</em> y la capacidad de autofinanciación alta, lo que implica que estas categorías tienden a acumular más frecuencias.</p>
<p>Pasamos ahora al <strong>modelo saturado</strong>, en el cuál se especifican todos los efectos directos o principales de los factores, y todas las interacciones posibles entre dichos factores (interacciones dos a dos, y la interacción entre los tres factores de modo simultáneo). Este modelo, en la práctica, no es relevante porque, aunque explica al 100% las frecuencias observadas, no indica cuál de los niveles de los factores o atributos y sus interacciones son los más relevantes (modelo redundante). Para su estimación, simplemente se sustituyen los signos “+” del modelo anterior por los signos “*”. El modelo se denominará “modelo_sat”:</p>
<div class="sourceCode" id="cb389"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="co"># Modelo Saturado.</span></span>
<span></span>
<span>    <span class="va">modelo_sat</span> <span class="op">&lt;-</span> <span class="fu">MASS</span><span class="fu">::</span><span class="fu"><a href="https://rdrr.io/pkg/MASS/man/loglm.html">loglm</a></span><span class="op">(</span><span class="op">~</span> <span class="va">DIMENSION</span> <span class="op">*</span> <span class="va">AUTOFINA</span> <span class="op">*</span> <span class="va">FJUR</span>,</span>
<span>                              data<span class="op">=</span> <span class="va">tab.originales2</span><span class="op">)</span></span>
<span></span>
<span>    <span class="fu">generar_solucion</span><span class="op">(</span><span class="va">modelo_sat</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-327-1.png" width="672"></div>
<p>El gráfico de mosaico muestra que, obviamente, todos los residuos son 0, ya que coinciden las frecuencias observadas y las estimadas por el modelo. En cuanto a la tabla de validación:</p>
<div class="sourceCode" id="cb390"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">solucion_modelo_sat</span><span class="op">$</span><span class="va">Informacion</span></span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-bordered table-condensed" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-327">Table 10.8: </span>Validación del modelo
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
Prueba
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Estadístico
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Grados Libertad
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
P-valor
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Likelihood Ratio
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Pearson
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
</tr>
</tbody>
</table></div>
<p>En ambas pruebas el p-valor es 1, dado que no se rechaza la hipótesis de que el modelo representa adecuadamente la realidad (de hecho, la representa perfectamente). Pero, como hemos dicho, desde el punto de vista del análisis estructural el modelo saturado no es muy útil, ya que no distingue entre los efectos e interacciones relevantes y los que son poco importantes. Por último, mostraremos la tabla con los coeficientes estimados, correspondientes tanto a los efectos principales o directos como a las interacciones:</p>
<div class="sourceCode" id="cb391"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">solucion_modelo_sat</span><span class="op">$</span><span class="va">Coeficientes</span></span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-bordered table-condensed" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-327">Table 10.8: </span>Coeficientes del modelo
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
Coefficient
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Value
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
T. Independiente
</td>
<td style="text-align:right;">
2.279
</td>
</tr>
<tr>
<td style="text-align:left;">
DIMENSION:GRANDE
</td>
<td style="text-align:right;">
0.239
</td>
</tr>
<tr>
<td style="text-align:left;">
DIMENSION:MEDIA
</td>
<td style="text-align:right;">
0.012
</td>
</tr>
<tr>
<td style="text-align:left;">
DIMENSION:REDUCIDA
</td>
<td style="text-align:right;">
-0.250
</td>
</tr>
<tr>
<td style="text-align:left;">
AUTOFINA:ALTA
</td>
<td style="text-align:right;">
0.606
</td>
</tr>
<tr>
<td style="text-align:left;">
AUTOFINA:NEGATIVA
</td>
<td style="text-align:right;">
-1.124
</td>
</tr>
<tr>
<td style="text-align:left;">
AUTOFINA:POSITIVA
</td>
<td style="text-align:right;">
0.517
</td>
</tr>
<tr>
<td style="text-align:left;">
FJUR:Sociedad anonima
</td>
<td style="text-align:right;">
-0.858
</td>
</tr>
<tr>
<td style="text-align:left;">
FJUR:Sociedad limitada
</td>
<td style="text-align:right;">
0.858
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:ALTA
</td>
<td style="text-align:right;">
0.542
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:NEGATIVA
</td>
<td style="text-align:right;">
-0.701
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:POSITIVA
</td>
<td style="text-align:right;">
0.159
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:ALTA
</td>
<td style="text-align:right;">
-0.547
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:NEGATIVA
</td>
<td style="text-align:right;">
0.566
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:POSITIVA
</td>
<td style="text-align:right;">
-0.019
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:ALTA
</td>
<td style="text-align:right;">
0.004
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:NEGATIVA
</td>
<td style="text-align:right;">
0.135
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:POSITIVA
</td>
<td style="text-align:right;">
-0.139
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:Sociedad anonima
</td>
<td style="text-align:right;">
0.315
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:Sociedad limitada
</td>
<td style="text-align:right;">
-0.315
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:Sociedad anonima
</td>
<td style="text-align:right;">
0.028
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:Sociedad limitada
</td>
<td style="text-align:right;">
-0.028
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.342
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:Sociedad limitada
</td>
<td style="text-align:right;">
0.342
</td>
</tr>
<tr>
<td style="text-align:left;">
ALTA:Sociedad anonima
</td>
<td style="text-align:right;">
0.146
</td>
</tr>
<tr>
<td style="text-align:left;">
ALTA:Sociedad limitada
</td>
<td style="text-align:right;">
-0.146
</td>
</tr>
<tr>
<td style="text-align:left;">
NEGATIVA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.067
</td>
</tr>
<tr>
<td style="text-align:left;">
NEGATIVA:Sociedad limitada
</td>
<td style="text-align:right;">
0.067
</td>
</tr>
<tr>
<td style="text-align:left;">
POSITIVA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.080
</td>
</tr>
<tr>
<td style="text-align:left;">
POSITIVA:Sociedad limitada
</td>
<td style="text-align:right;">
0.080
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:ALTA:Sociedad anonima
</td>
<td style="text-align:right;">
0.256
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:ALTA:Sociedad limitada
</td>
<td style="text-align:right;">
-0.256
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:NEGATIVA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.084
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:NEGATIVA:Sociedad limitada
</td>
<td style="text-align:right;">
0.084
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:POSITIVA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.173
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:POSITIVA:Sociedad limitada
</td>
<td style="text-align:right;">
0.173
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:ALTA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.057
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:ALTA:Sociedad limitada
</td>
<td style="text-align:right;">
0.057
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:NEGATIVA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.143
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:NEGATIVA:Sociedad limitada
</td>
<td style="text-align:right;">
0.143
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:POSITIVA:Sociedad anonima
</td>
<td style="text-align:right;">
0.201
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:POSITIVA:Sociedad limitada
</td>
<td style="text-align:right;">
-0.201
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:ALTA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.199
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:ALTA:Sociedad limitada
</td>
<td style="text-align:right;">
0.199
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:NEGATIVA:Sociedad anonima
</td>
<td style="text-align:right;">
0.227
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:NEGATIVA:Sociedad limitada
</td>
<td style="text-align:right;">
-0.227
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:POSITIVA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.028
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:POSITIVA:Sociedad limitada
</td>
<td style="text-align:right;">
0.028
</td>
</tr>
</tbody>
</table></div>
<p>La estimación del modelo saturado permite aplicar algún algoritmo para la obtención de la especificación de un modelo que, sin llegar a ser el saturado, <strong>asegure una representación valida de la realidad obviando los efectos e interacciones que no sean estadísticamente relevantes</strong>. Por ejemplo, un método es el <em>step / backward</em>, que, en función del <em>Criterio de Información de Akaike</em> (AIC), irá probando a estimar especificaciones más simples que disminuyan el AIC (lo que implica una mejor especificación). En nuestro caso, se aplicará con el código:</p>
<div class="sourceCode" id="cb392"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>  <span class="co"># Elección del modelo final.</span></span>
<span></span>
<span>    <span class="va">modelo_def</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/stats/step.html">step</a></span><span class="op">(</span><span class="va">modelo_sat</span>, scale <span class="op">=</span> <span class="fl">0</span>,</span>
<span>                       direction <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"backward"</span><span class="op">)</span>,</span>
<span>                       trace <span class="op">=</span> <span class="fl">1</span>, steps <span class="op">=</span> <span class="fl">1000</span><span class="op">)</span></span></code></pre></div>
<pre><code>## Start:  AIC=36
## ~DIMENSION * AUTOFINA * FJUR
## 
##                           Df    AIC
## - DIMENSION:AUTOFINA:FJUR  4 33.077
## &lt;none&gt;                       36.000
## 
## Step:  AIC=33.08
## ~DIMENSION + AUTOFINA + FJUR + DIMENSION:AUTOFINA + DIMENSION:FJUR + 
##     AUTOFINA:FJUR
## 
##                      Df    AIC
## &lt;none&gt;                  33.077
## - AUTOFINA:FJUR       2 36.975
## - DIMENSION:AUTOFINA  4 47.839
## - DIMENSION:FJUR      2 51.252</code></pre>
<p>En el código anterior, se genera el modelo óptimo siguiendo el proceso de eliminar los términos del modelo que más contribuyan a la reducción del valor de AIC, mediante la función <code><a href="https://rdrr.io/r/stats/step.html">step()</a></code>. El modelo así obtenido se guarda como “modelo_def”.</p>
<p>En nuestro ejemplo, la especificación del modelo definitivo incluye los tres efectos directos o principales de los factores o atributos, y todas las interacciones entre pares de factores; es decir, se diferencia del modelo saturado en la no inclusión de la interacción entre los tres factores o atributos de modo simultáneo.</p>
<p>Luego, se pasa el modelo a la función <code>generar_solución()</code> para obtener los resultados (el gráfico de mosaico y las dos tablas). El gráfico obtenido es:</p>
<div class="sourceCode" id="cb394"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="fu">generar_solucion</span><span class="op">(</span><span class="va">modelo_def</span><span class="op">)</span></span></code></pre></div>
<div class="inline-figure"><img src="RstarS_files/figure-html/unnamed-chunk-331-1.png" width="672"></div>
<p>Los tonos grisáceos y pardos indican que existen leves diferencias entre las frecuencias conjuntas observadas, y las estimadas por el modelo. En cuanto a la tabla de validación:</p>
<div class="sourceCode" id="cb395"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">solucion_modelo_def</span><span class="op">$</span><span class="va">Informacion</span></span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-bordered table-condensed" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-331">Table 10.9: </span>Validación del modelo
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
Prueba
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Estadístico
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Grados Libertad
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
P-valor
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
Likelihood Ratio
</td>
<td style="text-align:right;">
5.076509
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0.2795369
</td>
</tr>
<tr>
<td style="text-align:left;">
Pearson
</td>
<td style="text-align:right;">
5.277486
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
0.2599919
</td>
</tr>
</tbody>
</table></div>
<p>Las dos pruebas muestran un <em>p-valor</em> superior a 0,05, lo que implica, para ese nivel de significación, el <strong>no rechazo de la hipótesis nula de validez o idoneidad del modelo</strong> para representar la realidad adecuadamente. En cuanto a los coeficientes estimados del modelo:</p>
<div class="sourceCode" id="cb396"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span>    <span class="va">solucion_modelo_def</span><span class="op">$</span><span class="va">Coeficientes</span></span></code></pre></div>
<div class="inline-table"><table class="table table-striped table-bordered table-condensed" style="font-size: 12px; width: auto !important; margin-left: auto; margin-right: auto;">
<caption style="font-size: initial !important;">
<span id="tab:unnamed-chunk-331">Table 10.9: </span>Coeficientes del modelo
</caption>
<thead><tr>
<th style="text-align:left;font-weight: bold;text-align: center;">
Coefficient
</th>
<th style="text-align:right;font-weight: bold;text-align: center;">
Value
</th>
</tr></thead>
<tbody>
<tr>
<td style="text-align:left;">
T. Independiente
</td>
<td style="text-align:right;">
2.255
</td>
</tr>
<tr>
<td style="text-align:left;">
DIMENSION:GRANDE
</td>
<td style="text-align:right;">
0.303
</td>
</tr>
<tr>
<td style="text-align:left;">
DIMENSION:MEDIA
</td>
<td style="text-align:right;">
0.056
</td>
</tr>
<tr>
<td style="text-align:left;">
DIMENSION:REDUCIDA
</td>
<td style="text-align:right;">
-0.359
</td>
</tr>
<tr>
<td style="text-align:left;">
AUTOFINA:ALTA
</td>
<td style="text-align:right;">
0.711
</td>
</tr>
<tr>
<td style="text-align:left;">
AUTOFINA:NEGATIVA
</td>
<td style="text-align:right;">
-1.183
</td>
</tr>
<tr>
<td style="text-align:left;">
AUTOFINA:POSITIVA
</td>
<td style="text-align:right;">
0.472
</td>
</tr>
<tr>
<td style="text-align:left;">
FJUR:Sociedad anonima
</td>
<td style="text-align:right;">
-0.880
</td>
</tr>
<tr>
<td style="text-align:left;">
FJUR:Sociedad limitada
</td>
<td style="text-align:right;">
0.880
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:ALTA
</td>
<td style="text-align:right;">
0.381
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:NEGATIVA
</td>
<td style="text-align:right;">
-0.644
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:POSITIVA
</td>
<td style="text-align:right;">
0.263
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:ALTA
</td>
<td style="text-align:right;">
-0.551
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:NEGATIVA
</td>
<td style="text-align:right;">
0.693
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:POSITIVA
</td>
<td style="text-align:right;">
-0.142
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:ALTA
</td>
<td style="text-align:right;">
0.170
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:NEGATIVA
</td>
<td style="text-align:right;">
-0.049
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:POSITIVA
</td>
<td style="text-align:right;">
-0.121
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:Sociedad anonima
</td>
<td style="text-align:right;">
0.384
</td>
</tr>
<tr>
<td style="text-align:left;">
GRANDE:Sociedad limitada
</td>
<td style="text-align:right;">
-0.384
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:Sociedad anonima
</td>
<td style="text-align:right;">
0.088
</td>
</tr>
<tr>
<td style="text-align:left;">
MEDIA:Sociedad limitada
</td>
<td style="text-align:right;">
-0.088
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.472
</td>
</tr>
<tr>
<td style="text-align:left;">
REDUCIDA:Sociedad limitada
</td>
<td style="text-align:right;">
0.472
</td>
</tr>
<tr>
<td style="text-align:left;">
ALTA:Sociedad anonima
</td>
<td style="text-align:right;">
0.267
</td>
</tr>
<tr>
<td style="text-align:left;">
ALTA:Sociedad limitada
</td>
<td style="text-align:right;">
-0.267
</td>
</tr>
<tr>
<td style="text-align:left;">
NEGATIVA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.131
</td>
</tr>
<tr>
<td style="text-align:left;">
NEGATIVA:Sociedad limitada
</td>
<td style="text-align:right;">
0.131
</td>
</tr>
<tr>
<td style="text-align:left;">
POSITIVA:Sociedad anonima
</td>
<td style="text-align:right;">
-0.135
</td>
</tr>
<tr>
<td style="text-align:left;">
POSITIVA:Sociedad limitada
</td>
<td style="text-align:right;">
0.135
</td>
</tr>
</tbody>
</table></div>
<p>En la tabla anterior detaca, dentro de los efectos directos o principales, el coeficiente negativo de la capacidad de autofinanciación negativa y el de forma jurídica de <em>Sociedad Anónima</em> como principales categorías que influyen en la disminución de las frecuencias conjuntas implicadas. En el extremo opuesto se encuentra el coeficiente correspondiente a la forma jurídica de <em>Sociedad Limitada</em>. En cuanto a las interacciones entre factores, se comprueba que la simultaneidad entre una dimensión de la matriz grande y una capacidad de autofinanciación negativa parece influir en una reducción significativa de las frecuencias conjuntas implicadas. Lo mismo ocurre con la simultaneidad entre una dimensión de la empresa matriz media y una capacidad de autofinanciación alta, y entre una dimensión de la empresa matriz reducida y la forma jurídica de <em>Sociedad Anónima</em>. En el extremo opuesto, hay ciertas interacciones que parecen inluir en que las frecuencias conjuntas implicadas aumenten, como por ejemplo una dimensión de la matriz reducida y una capacidad de autofinanciación negativa, o de nuevo una dimensión de la matriz empresarial reducida con una forma jurídica de <em>Sociedad Limitada</em>.</p>
</div>
<div id="materiales-para-realizar-las-prácticas-del-capítulo.-8" class="section level2" number="10.5">
<h2>
<span class="header-section-number">10.5</span> Materiales para realizar las prácticas del capítulo.<a class="anchor" aria-label="anchor" href="#materiales-para-realizar-las-pr%C3%A1cticas-del-cap%C3%ADtulo.-8"><i class="fas fa-link"></i></a>
</h2>
<p>En esta sección se muestran los links de acceso a los diferentes materiales (<em>scripts</em>, datos…) necesarios para llevar a cabo los contenidos prácticos del capítulo.</p>
<p><strong>Datos (en formato Microsoft (R) Excel (R)):</strong></p>
<ul>
<li><p>eolica_contingencia.xlsx (<a href="https://docs.google.com/spreadsheets/d/1N5QIRKbm6OKAOaN8DB2YFDptpZ_0pbPc/edit?usp=sharing&amp;ouid=115375878280465826079&amp;rtpof=true&amp;sd=true">obtener aquí</a>)</p></li>
<li><p>eolica_contingencia2.xlsx (<a href="https://docs.google.com/spreadsheets/d/1f0OQaxyzjKIIXrqhCFL1vIBNcLLGx6R4/edit?usp=sharing&amp;ouid=115375878280465826079&amp;rtpof=true&amp;sd=true">obtener aquí</a>)</p></li>
<li><p><strong>Scripts:</strong></p></li>
<li><p>correspondencias_eolica.R <a href="https://drive.google.com/file/d/1p4p17OudRprwkpF7wvvF1gwHZG82uv89/view?usp=sharing">(</a><a href="https://drive.google.com/file/d/1u8gJa3jQH2cwuQ8KsISQ9esHKrFAO_au/view?usp=sharing">obtener aquí</a>)</p></li>
<li><p>loglineal_eolica.R (<a href="https://drive.google.com/file/d/1xMmM2nrSHBCMU1EEDePb2BRuv_TbD-7r/view?usp=sharing">obtener aquí</a>)</p></li>
</ul>
</div>
</div>
  <div class="chapter-nav">
<div class="prev"><a href="an%C3%A1lisis-de-regresi%C3%B3n-lineal-m%C3%BAltiple..html"><span class="header-section-number">9</span> Análisis de Regresión Lineal Múltiple.</a></div>
<div class="next"><a href="bibliograf%C3%ADa.html">Bibliografía</a></div>
</div></main><div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page"><h2>On this page</h2>
      <ul class="nav navbar-nav">
<li><a class="nav-link" href="#an%C3%A1lisis-de-datos-cualitativos."><span class="header-section-number">10</span> Análisis de Datos Cualitativos.</a></li>
<li><a class="nav-link" href="#introducci%C3%B3n.-6"><span class="header-section-number">10.1</span> Introducción.</a></li>
<li><a class="nav-link" href="#tablas-de-contingencia-y-asociaci%C3%B3n-entre-dos-atributos-o-factores."><span class="header-section-number">10.2</span> Tablas de contingencia, y asociación entre dos atributos o factores.</a></li>
<li><a class="nav-link" href="#an%C3%A1lisis-de-correspondencias."><span class="header-section-number">10.3</span> Análisis de correspondencias.</a></li>
<li><a class="nav-link" href="#modelos-logaritmico-lineales-aplicados-a-tablas-de-contingencia."><span class="header-section-number">10.4</span> Modelos logaritmico-lineales aplicados a tablas de contingencia.</a></li>
<li><a class="nav-link" href="#materiales-para-realizar-las-pr%C3%A1cticas-del-cap%C3%ADtulo.-8"><span class="header-section-number">10.5</span> Materiales para realizar las prácticas del capítulo.</a></li>
</ul>

      <div class="book-extra">
        <ul class="list-unstyled">
          
        </ul>
</div>
    </nav>
</div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5"><div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>R-Stars: La Guía</strong>" was written by Miguel-Ángel Tarancón. It was last built on 2025-10-02.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer><!-- dynamically load mathjax for compatibility with self-contained --><script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script><script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>
</html>
